# Generated by Django 5.2.5 on 2026-08-24 19:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("rehearsal", "Rehearsal"),
                            ("content", "Content"),
                            ("press", "Press"),
                            ("admin", "Administration"),
                            ("reminder", "Reminder"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=5000)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("all_day", models.BooleanField(default=False)),
                ("timezone", models.CharField(default="Africa/Johannesburg", max_length=64)),
                ("location", models.CharField(blank=True, max_length=300)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("artist_team", "Artist team"),
                            ("private", "Private"),
                        ],
                        default="organization",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_events",
                        to="artists.artist",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_calendar_events",
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at", "title"),
                "indexes": [
                    models.Index(
                        fields=["organization", "starts_at", "status"],
                        name="calendar_ap_organiz_5e3b37_idx",
                    )
                ],
            },
        ),
    ]
