# Generated by Django 5.2.5 on 2026-08-24 14:53

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import bookings.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("contacts", "0001_initial"),
        ("organizations", "0002_initial"),
        ("promoters", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=bookings.models.booking_reference,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enquiry", "Enquiry"),
                            ("hold", "Hold"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined"),
                        ],
                        default="enquiry",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField()),
                ("event_start_datetime", models.DateTimeField(blank=True, null=True)),
                ("event_end_datetime", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="Africa/Johannesburg", max_length=64)),
                ("venue_name_snapshot", models.CharField(blank=True, max_length=180)),
                ("city_snapshot", models.CharField(blank=True, max_length=120)),
                ("country_snapshot", models.CharField(blank=True, max_length=100)),
                ("promoter_name_snapshot", models.CharField(blank=True, max_length=180)),
                (
                    "currency",
                    models.CharField(
                        default="ZAR",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three-letter uppercase currency code."
                            )
                        ],
                    ),
                ),
                (
                    "performance_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("deposit_due_date", models.DateField(blank=True, null=True)),
                ("balance_due_date", models.DateField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True, max_length=10000)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="artists.artist",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="promoters.promoter",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ("event_date", "title"),
            },
        ),
        migrations.CreateModel(
            name="BookingContactAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "responsibility",
                    models.CharField(
                        choices=[
                            ("booking", "Booking"),
                            ("promoter", "Promoter"),
                            ("venue", "Venue"),
                            ("production", "Production"),
                            ("finance", "Finance"),
                            ("hospitality", "Hospitality"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("snapshot_name", models.CharField(max_length=241)),
                ("snapshot_email", models.EmailField(blank=True, max_length=254)),
                ("snapshot_phone", models.CharField(blank=True, max_length=40)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_assignments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_assignments",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "responsibility", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="BookingStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("enquiry", "Enquiry"),
                            ("hold", "Hold"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("enquiry", "Enquiry"),
                            ("hold", "Hold"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="bookings.booking",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BookingTeamAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "responsibility",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("booking", "Booking"),
                            ("production", "Production"),
                            ("finance", "Finance"),
                            ("marketing", "Marketing"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_assignments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_assignments",
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "responsibility", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["organization", "event_date"], name="bookings_bo_organiz_e25086_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["organization", "status", "priority"], name="bookings_bo_organiz_6f35aa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingcontactassignment",
            constraint=models.UniqueConstraint(
                fields=("booking", "contact", "responsibility"),
                name="unique_booking_contact_responsibility",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingcontactassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("booking", "responsibility"),
                name="one_primary_booking_contact_per_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingteamassignment",
            constraint=models.UniqueConstraint(
                fields=("booking", "membership"), name="unique_booking_membership_assignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingteamassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("booking",),
                name="one_active_primary_booking_assignment",
            ),
        ),
    ]
