# Generated by Django 5.2.5 on 2026-08-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("team", "Team"),
                    ("bookings", "Bookings"),
                    ("call_sheets", "Call sheets"),
                    ("music", "Music"),
                    ("marketing", "Marketing"),
                    ("documents", "Documents"),
                    ("finance", "Finance"),
                    ("rights", "Rights & royalties"),
                    ("system", "System"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="category",
            field=models.CharField(
                choices=[
                    ("team", "Team"),
                    ("bookings", "Bookings"),
                    ("call_sheets", "Call sheets"),
                    ("music", "Music"),
                    ("marketing", "Marketing"),
                    ("documents", "Documents"),
                    ("finance", "Finance"),
                    ("rights", "Rights & royalties"),
                    ("system", "System"),
                ],
                max_length=24,
            ),
        ),
    ]
