# Generated by Django 5.2.5 on 2026-09-12 00:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_alter_emailconnector_secret_reference_and_more"),
        ("notifications", "0003_alter_notification_category_and_more"),
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("team", "Team"),
                    ("bookings", "Bookings"),
                    ("call_sheets", "Call sheets"),
                    ("music", "Music"),
                    ("marketing", "Marketing"),
                    ("documents", "Documents"),
                    ("finance", "Finance"),
                    ("rights", "Rights & royalties"),
                    ("contracts", "Contracts"),
                    ("production", "Production"),
                    ("security", "Security"),
                    ("system", "System"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="category",
            field=models.CharField(
                choices=[
                    ("team", "Team"),
                    ("bookings", "Bookings"),
                    ("call_sheets", "Call sheets"),
                    ("music", "Music"),
                    ("marketing", "Marketing"),
                    ("documents", "Documents"),
                    ("finance", "Finance"),
                    ("rights", "Rights & royalties"),
                    ("contracts", "Contracts"),
                    ("production", "Production"),
                    ("security", "Security"),
                    ("system", "System"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="EmailDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("category", models.CharField(max_length=24)),
                ("template_key", models.CharField(max_length=80)),
                ("recipient_email_snapshot", models.EmailField(max_length=254)),
                ("subject_snapshot", models.CharField(max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("not_configured", "Not configured"),
                            ("suppressed", "Suppressed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("failure_code", models.CharField(blank=True, max_length=40)),
                ("failure_message", models.CharField(blank=True, max_length=240)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=120, null=True, unique=True),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_attempts",
                        to="integrations.emailconnector",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_attempts",
                        to="notifications.notification",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_delivery_attempts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_delivery_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-attempted_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "attempted_at"], name="notificatio_status_01cdba_idx"
                    ),
                    models.Index(
                        fields=["organization", "attempted_at"],
                        name="notificatio_organiz_e37015_idx",
                    ),
                    models.Index(
                        fields=["connector", "attempted_at"], name="notificatio_connect_961a6d_idx"
                    ),
                    models.Index(
                        fields=["user", "attempted_at"], name="notificatio_user_id_bb467a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("notification", "user", "attempt_number"),
                        name="unique_notification_email_attempt",
                    )
                ],
            },
        ),
    ]
