# Generated by Django 5.2.5 on 2026-09-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("notifications", "0005_devicepushsubscription")]

    operations = [
        migrations.RenameIndex(
            model_name="devicepushsubscription",
            old_name="notificatio_user_id_7c2bb1_idx",
            new_name="notificatio_user_id_54a11f_idx",
        ),
    ]
