# Generated by Django 5.2.5 on 2026-08-24 12:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import white_label.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIClient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_clients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_clients",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key_prefix", models.CharField(max_length=16, unique=True)),
                ("secret_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="white_label.apiclient",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationBranding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("logo_url", models.URLField(blank=True, max_length=500)),
                ("favicon_url", models.URLField(blank=True, max_length=500)),
                (
                    "primary_color",
                    models.CharField(
                        default="#D6A84B",
                        max_length=7,
                        validators=[white_label.models.validate_hex_color],
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#A3A3A3",
                        max_length=7,
                        validators=[white_label.models.validate_hex_color],
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#F0C96B",
                        max_length=7,
                        validators=[white_label.models.validate_hex_color],
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#0A0A0A",
                        max_length=7,
                        validators=[white_label.models.validate_hex_color],
                    ),
                ),
                (
                    "surface_color",
                    models.CharField(
                        default="#171717",
                        max_length=7,
                        validators=[white_label.models.validate_hex_color],
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#FAFAFA",
                        max_length=7,
                        validators=[white_label.models.validate_hex_color],
                    ),
                ),
                (
                    "text_muted_color",
                    models.CharField(
                        default="#A3A3A3",
                        max_length=7,
                        validators=[white_label.models.validate_hex_color],
                    ),
                ),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_url", models.URLField(blank=True, max_length=500)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization__name",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationDomain",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        max_length=253,
                        unique=True,
                        validators=[white_label.models.validate_hostname],
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("verified", "Verified")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_token", models.CharField(editable=False, max_length=64)),
                ("verified_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("hostname",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("is_primary", True)),
                        fields=("organization",),
                        name="one_active_primary_domain_per_organization",
                    )
                ],
            },
        ),
    ]
