# Generated by Django 5.2.5 on 2026-09-27 11:52

import uuid
import white_label.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0002_branding_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBranding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('override_organizations', models.BooleanField(default=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('favicon_url', models.URLField(blank=True, max_length=500)),
                ('primary_color', models.CharField(blank=True, max_length=7, validators=[white_label.models.validate_hex_color])),
                ('secondary_color', models.CharField(blank=True, max_length=7, validators=[white_label.models.validate_hex_color])),
                ('accent_color', models.CharField(blank=True, max_length=7, validators=[white_label.models.validate_hex_color])),
                ('background_color', models.CharField(blank=True, max_length=7, validators=[white_label.models.validate_hex_color])),
                ('surface_color', models.CharField(blank=True, max_length=7, validators=[white_label.models.validate_hex_color])),
                ('text_color', models.CharField(blank=True, max_length=7, validators=[white_label.models.validate_hex_color])),
                ('text_muted_color', models.CharField(blank=True, max_length=7, validators=[white_label.models.validate_hex_color])),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('og_image_url', models.URLField(blank=True, max_length=500)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
