# Generated by Django 5.2.5 on 2026-09-27 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_googleworkspaceconnector_refresh_token_reference'),
        ('white_label', '0003_globalbranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBrandingAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon')], max_length=20)),
                ('storage_key', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=180)),
                ('content_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('branding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='white_label.globalbranding')),
                ('storage_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_branding_assets', to='integrations.storageprovider')),
            ],
            options={
                'ordering': ('asset_type',),
                'constraints': [models.UniqueConstraint(fields=('branding', 'asset_type'), name='one_global_branding_asset_per_type')],
            },
        ),
    ]
