# Generated by Django 5.2.5 on 2026-08-28 09:15

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import contracts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("bookings", "0001_initial"),
        ("contacts", "0001_initial"),
        ("documents", "0005_documentlink_production_advance_and_more"),
        ("organizations", "0002_initial"),
        ("promoters", "0001_initial"),
        ("rights", "0002_work_source_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("performance", "Performance"),
                            ("artist_services", "Artist services"),
                            ("management", "Management"),
                            ("booking", "Booking"),
                            ("promoter", "Promoter"),
                            ("venue", "Venue"),
                            ("recording", "Recording"),
                            ("release", "Release"),
                            ("licensing", "Licensing"),
                            ("publishing", "Publishing"),
                            ("production", "Production"),
                            ("sponsorship", "Sponsorship"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=contracts.models.contract_reference,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In review"),
                            ("approved", "Approved"),
                            ("sent", "Sent"),
                            ("partially_signed", "Partially signed"),
                            ("executed", "Executed"),
                            ("terminated", "Terminated"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("signed_date", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use an uppercase three-letter currency code."
                            )
                        ],
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
                ),
                ("governing_law", models.CharField(blank=True, max_length=160)),
                ("jurisdiction", models.CharField(blank=True, max_length=160)),
                ("summary", models.TextField(blank=True, max_length=5000)),
                ("internal_notes", models.TextField(blank=True, max_length=5000)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                ("termination_reason", models.CharField(blank=True, max_length=500)),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="artists.artist",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="promoters.promoter",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="ContractApproval",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, max_length=2000)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="contracts.contract",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_approvals",
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "requested_at"),
            },
        ),
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="contracts.contract",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_links",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractParty",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("artist", "Artist"),
                            ("manager", "Manager"),
                            ("promoter", "Promoter"),
                            ("venue", "Venue"),
                            ("label", "Label"),
                            ("publisher", "Publisher"),
                            ("producer", "Producer"),
                            ("sponsor", "Sponsor"),
                            ("client", "Client"),
                            ("agent", "Agent"),
                            ("licensor", "Licensor"),
                            ("licensee", "Licensee"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(max_length=220)),
                ("legal_name", models.CharField(blank=True, max_length=220)),
                ("email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("address_snapshot", models.TextField(blank=True, max_length=1000)),
                ("is_signatory", models.BooleanField(default=False)),
                (
                    "signing_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("pending", "Pending"),
                            ("signed", "Signed"),
                            ("declined", "Declined"),
                        ],
                        default="not_required",
                        max_length=20,
                    ),
                ),
                ("signing_order", models.PositiveIntegerField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signing_note", models.CharField(blank=True, max_length=500)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parties",
                        to="contracts.contract",
                    ),
                ),
                (
                    "linked_artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_parties",
                        to="artists.artist",
                    ),
                ),
                (
                    "linked_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_parties",
                        to="contacts.contact",
                    ),
                ),
                (
                    "linked_promoter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_parties",
                        to="promoters.promoter",
                    ),
                ),
                (
                    "linked_rights_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_parties",
                        to="rights.rightsparty",
                    ),
                ),
            ],
            options={
                "ordering": ("signing_order", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ContractSection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("scope", "Scope"),
                            ("payment", "Payment"),
                            ("cancellation", "Cancellation"),
                            ("obligations", "Obligations"),
                            ("rights", "Rights"),
                            ("confidentiality", "Confidentiality"),
                            ("termination", "Termination"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("body", models.TextField(max_length=10000)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ContractTerm",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "term_type",
                    models.CharField(
                        choices=[
                            ("fee", "Fee"),
                            ("deposit", "Deposit"),
                            ("payment_due", "Payment due"),
                            ("cancellation", "Cancellation"),
                            ("term_length", "Term length"),
                            ("exclusivity", "Exclusivity"),
                            ("territory", "Territory"),
                            ("notice", "Notice"),
                            ("deliverable", "Deliverable"),
                            ("usage_right", "Usage right"),
                            ("commission", "Commission"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("value_text", models.TextField(blank=True, max_length=2000)),
                (
                    "value_decimal",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use an uppercase three-letter currency code."
                            )
                        ],
                    ),
                ),
                ("date_value", models.DateField(blank=True, null=True)),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=2000)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terms",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["organization", "status", "expiry_date"],
                name="contracts_c_organiz_cad1e0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractapproval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("contract", "membership"),
                name="contract_one_pending_approval",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractdocument",
            constraint=models.UniqueConstraint(
                fields=("contract", "document"), name="contract_unique_document_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractsection",
            constraint=models.UniqueConstraint(
                fields=("contract", "sequence"), name="contract_unique_section_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractterm",
            constraint=models.UniqueConstraint(
                fields=("contract", "sequence"), name="contract_unique_term_sequence"
            ),
        ),
    ]
