# Generated by Django 5.2.5 on 2026-08-24 14:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("job_title", models.CharField(blank=True, max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("mobile", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True, max_length=5000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("last_name", "first_name"),
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"], name="contacts_co_organiz_b3a4e2_idx"
                    )
                ],
            },
        ),
    ]
