# Generated by Django 5.2.5 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("member", "Member"),
                    ("artist", "Artist"),
                    ("artist_manager", "Artist manager"),
                    ("artist_assistant", "Artist assistant"),
                    ("artist_viewer", "Artist viewer"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("member", "Member"),
                    ("artist", "Artist"),
                    ("artist_manager", "Artist manager"),
                    ("artist_assistant", "Artist assistant"),
                    ("artist_viewer", "Artist viewer"),
                ],
                max_length=20,
            ),
        ),
    ]
