# Generated by Django 5.2.5 on 2026-08-28 15:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import integrations.validation


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConnector",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "provider_type",
                    models.CharField(choices=[("smtp", "SMTP")], default="smtp", max_length=20),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("from_name", models.CharField(max_length=120)),
                ("from_email", models.EmailField(max_length=254)),
                ("reply_to_email", models.EmailField(blank=True, max_length=254)),
                ("host", models.CharField(max_length=253)),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=587,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                ("use_tls", models.BooleanField(default=True)),
                ("use_ssl", models.BooleanField(default=False)),
                ("username", models.CharField(blank=True, max_length=253)),
                (
                    "secret_reference",
                    models.CharField(
                        max_length=110,
                        validators=[integrations.validation.validate_secret_reference],
                    ),
                ),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("never_tested", "Never tested"),
                            ("healthy", "Healthy"),
                            ("failed", "Failed"),
                        ],
                        default="never_tested",
                        max_length=20,
                    ),
                ),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_message", models.CharField(blank=True, max_length=240)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="one_default_email_connector",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StorageProvider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("s3_compatible", "S3 compatible"), ("aws_s3", "AWS S3")],
                        default="s3_compatible",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("endpoint", models.URLField(max_length=500)),
                ("region", models.CharField(max_length=80)),
                (
                    "bucket",
                    models.CharField(
                        max_length=63,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$",
                                "Use a valid lowercase bucket name.",
                            )
                        ],
                    ),
                ),
                (
                    "path_prefix",
                    models.CharField(
                        blank=True,
                        max_length=180,
                        validators=[integrations.validation.validate_path_prefix],
                    ),
                ),
                ("public_base_url", models.URLField(blank=True, max_length=500)),
                (
                    "access_key_reference",
                    models.CharField(
                        max_length=110,
                        validators=[integrations.validation.validate_secret_reference],
                    ),
                ),
                (
                    "secret_key_reference",
                    models.CharField(
                        max_length=110,
                        validators=[integrations.validation.validate_secret_reference],
                    ),
                ),
                ("use_ssl", models.BooleanField(default=True)),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("never_tested", "Never tested"),
                            ("healthy", "Healthy"),
                            ("failed", "Failed"),
                        ],
                        default="never_tested",
                        max_length=20,
                    ),
                ),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_message", models.CharField(blank=True, max_length=240)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="one_default_storage_provider",
                    )
                ],
            },
        ),
    ]
