# Generated by Django 5.2.5 on 2026-08-28 16:02

from django.db import migrations, models

import integrations.validation


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconnector",
            name="secret_reference",
            field=models.CharField(
                max_length=110, validators=[integrations.validation.validate_email_secret_reference]
            ),
        ),
        migrations.AlterField(
            model_name="storageprovider",
            name="access_key_reference",
            field=models.CharField(
                max_length=110,
                validators=[integrations.validation.validate_storage_secret_reference],
            ),
        ),
        migrations.AlterField(
            model_name="storageprovider",
            name="secret_key_reference",
            field=models.CharField(
                max_length=110,
                validators=[integrations.validation.validate_storage_secret_reference],
            ),
        ),
    ]
