# Generated by Django 5.2.5 on 2026-09-12 21:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_alter_emailconnector_secret_reference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoragePolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("max_document_size_bytes", models.PositiveBigIntegerField(default=26214400)),
                ("max_image_size_bytes", models.PositiveBigIntegerField(default=15728640)),
                ("max_audio_size_bytes", models.PositiveBigIntegerField(default=262144000)),
                ("max_video_size_bytes", models.PositiveBigIntegerField(default=26214400)),
                ("audio_upload_enabled", models.BooleanField(default=False)),
                ("video_upload_enabled", models.BooleanField(default=False)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_document_size_bytes__gt", 0)),
                        name="storage_policy_document_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_image_size_bytes__gt", 0)),
                        name="storage_policy_image_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_audio_size_bytes__gt", 0)),
                        name="storage_policy_audio_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_video_size_bytes__gt", 0)),
                        name="storage_policy_video_positive",
                    ),
                ],
            },
        ),
    ]
