# Generated by Django 5.2.5 on 2026-09-27 10:34

import integrations.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_allow_unauthenticated_smtp_relay'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleworkspaceconnector',
            name='refresh_token_reference',
            field=models.CharField(blank=True, max_length=220, validators=[integrations.validation.validate_google_secret_reference]),
        ),
    ]
