"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { RouteGuard } from "@/components/auth/route-guard";
import { useAuth } from "@/components/auth/auth-provider";
import { apiRequest } from "@/lib/api/client";
import { buttonClass, EmptyState, fieldClass, PageHeader, secondaryButtonClass, StatCard, StatusBadge } from "@/components/ui/page";

interface Organization { id: string; name: string; slug: string; is_active: boolean; created_at: string; updated_at: string; member_count: number; pending_invitation_count: number; artist_count: number; active_artist_count: number; inactive_artist_count: number; promoter_count: number; venue_count: number; contact_count: number; booking_count: number; upcoming_booking_count: number; confirmed_booking_count: number; pending_booking_count: number; priority_booking_count: number; }
interface Member { id: string; user: { id: string; email: string; first_name: string; last_name: string; is_active: boolean }; organization: { id: string; name: string; slug: string }; role: string; is_active: boolean; created_at: string; }
interface Invitation { id: string; email: string; role: string; invited_by: string | null; created_at: string; expires_at: string; status: string; token?: string; }
interface PlatformUser { id: string; email: string; first_name: string; last_name: string; is_active: boolean; is_staff: boolean; is_superuser: boolean; membership_count: number; date_joined: string; last_login: string | null; memberships?: Member[]; }
interface AuditEvent { id: string; created_at: string; actor: string | null; organization: string | null; action: string; resource_type: string; description: string; ip_address: string | null; }

function useResource<T>(path: string | null) {
  const [data, setData] = useState<T | null>(null);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    if (!path) return;
    setError("");
    try { setData(await apiRequest<T>(path)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load data."); }
  }, [path]);
  useEffect(() => {
    if (!path) return;
    let cancelled = false;
    apiRequest<T>(path)
      .then((next) => { if (!cancelled) setData(next); })
      .catch((caught) => { if (!cancelled) setError(caught instanceof Error ? caught.message : "Unable to load data."); });
    return () => { cancelled = true; };
  }, [path]);
  return { data, error, load, setData };
}

function Notice({ message, error = false }: { message: string; error?: boolean }) {
  if (!message) return null;
  return <p aria-live="polite" className={`rounded-md border px-4 py-3 text-sm ${error ? "border-red-900 bg-red-950 text-red-200" : "border-emerald-900 bg-emerald-950 text-emerald-200"}`}>{message}</p>;
}

function Loading() { return <p className="py-12 text-sm text-neutral-500">Loading current data...</p>; }
function WorkspaceFrame({ children }: { children: React.ReactNode }) { return <RouteGuard portal="workspace"><AppShell organizationScoped>{children}</AppShell></RouteGuard>; }
function PlatformFrame({ children }: { children: React.ReactNode }) { return <RouteGuard portal="platform"><AppShell>{children}</AppShell></RouteGuard>; }

export function DashboardPage() {
  const { session, activeOrganizationId } = useAuth();
  const path = session?.user.is_superuser ? "/api/platform/overview/" : activeOrganizationId ? `/api/organizations/${activeOrganizationId}/` : null;
  const { data } = useResource<Organization & Record<string, number>>(path);
  const membership = session?.memberships.find((item) => item.organization.id === activeOrganizationId);
  return <RouteGuard portal="dashboard"><AppShell><PageHeader eyebrow="Home" title="Dashboard" description="Live identity, organization, and booking information." actions={membership?.permissions.includes("booking.manage") ? <Link className={buttonClass} href="/workspace/bookings/new">Create booking</Link> : undefined}/><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{session?.user.is_superuser ? <><StatCard label="Organizations" value={data?.organizations ?? "-"} /><StatCard label="Active users" value={data?.active_users ?? "-"} /><StatCard label="Artists" value={data?.artists ?? "-"} /><StatCard label="Bookings" value={data?.bookings ?? "-"} /><StatCard label="Upcoming bookings" value={data?.upcoming_bookings ?? "-"} /><StatCard label="Promoters" value={data?.promoters ?? "-"} /><StatCard label="Venues" value={data?.venues ?? "-"} /></> : data ? <><StatCard label="Current organization" value={data.name} /><StatCard label="Upcoming bookings" value={data.upcoming_booking_count} /><StatCard label="Confirmed" value={data.confirmed_booking_count} /><StatCard label="Pending / hold" value={data.pending_booking_count} /><StatCard label="High priority" value={data.priority_booking_count} /><StatCard label="Active artists" value={data.active_artist_count} /><StatCard label="Promoters" value={data.promoter_count} /><StatCard label="Venues" value={data.venue_count} /></> : <StatCard label="Active organizations" value={session?.memberships.length ?? 0} />}</div></AppShell></RouteGuard>;
}

export function WorkspaceOverviewPage() {
  const { activeOrganizationId, session } = useAuth();
  const { data, error } = useResource<Organization>(activeOrganizationId ? `/api/organizations/${activeOrganizationId}/` : null);
  const membership = session?.memberships.find((item) => item.organization.id === activeOrganizationId);
  return <WorkspaceFrame><PageHeader eyebrow="Workspace" title={data?.name ?? "Organization overview"} description="Current organization access, team, booking, and invitation status." /><Notice message={error} error />{data ? <><div className="mt-7 grid gap-4 sm:grid-cols-3"><StatCard label="Your role" value={membership?.role ?? "-"} /><StatCard label="Upcoming bookings" value={data.upcoming_booking_count} /><StatCard label="Confirmed bookings" value={data.confirmed_booking_count} /></div><div className="mt-7 flex flex-wrap gap-3">{membership?.permissions.includes("booking.manage")&&<Link className={buttonClass} href="/workspace/bookings/new">Create booking</Link>}{membership?.permissions.includes("artist.view")&&<Link className={secondaryButtonClass} href="/workspace/artists/new">Add artist</Link>}{membership?.permissions.includes("promoter.manage")&&<Link className={secondaryButtonClass} href="/workspace/promoters/new">Add promoter</Link>}{membership?.permissions.includes("venue.manage")&&<Link className={secondaryButtonClass} href="/workspace/venues/new">Add venue</Link>}</div><div className="mt-7 flex flex-wrap gap-3"><Link className={buttonClass} href="/workspace/team">Manage team</Link><Link className={secondaryButtonClass} href="/workspace/invitations">Invitations</Link><Link className={secondaryButtonClass} href="/workspace/organization">Organization settings</Link></div></> : <Loading />}</WorkspaceFrame>;
}

export function TeamPage() {
  const { activeOrganizationId, session } = useAuth();
  const path = activeOrganizationId ? `/api/organizations/${activeOrganizationId}/members/` : null;
  const { data, error, load } = useResource<Member[]>(path);
  const [query, setQuery] = useState(""); const [role, setRole] = useState(""); const [status, setStatus] = useState(""); const [message, setMessage] = useState("");
  const membership = session?.memberships.find((item) => item.organization.id === activeOrganizationId);
  const canManage = membership?.permissions.includes("membership.manage");
  const filtered = useMemo(() => (data ?? []).filter((item) => (!query || `${item.user.first_name} ${item.user.last_name} ${item.user.email}`.toLowerCase().includes(query.toLowerCase())) && (!role || item.role === role) && (!status || String(item.is_active) === status)), [data, query, role, status]);
  async function update(item: Member, patch: Partial<Member>) { if (!path || !confirm("Apply this membership access change?")) return; setMessage(""); try { await apiRequest(`${path}${item.id}/`, { method: "PATCH", body: JSON.stringify(patch) }); setMessage("Membership updated."); await load(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Unable to update membership."); } }
  return <WorkspaceFrame><PageHeader eyebrow="Workspace" title="Team" description="Organization membership, roles, and access status." /><div className="mt-6 grid gap-3 sm:grid-cols-3"><input className={fieldClass} placeholder="Search name or email" value={query} onChange={(e) => setQuery(e.target.value)} /><select className={fieldClass} value={role} onChange={(e) => setRole(e.target.value)}><option value="">All roles</option>{["owner","admin","manager","member","artist"].map((value) => <option key={value}>{value}</option>)}</select><select className={fieldClass} value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div><div className="mt-4"><Notice message={error || message} error={!!error || message.includes("cannot")} /></div>{!data ? <Loading /> : filtered.length === 0 ? <div className="mt-7"><EmptyState title="No team members" detail="No memberships match the current filters." /></div> : <div className="mt-7 overflow-x-auto rounded-md border border-neutral-800"><table className="w-full min-w-176 text-left text-sm"><thead className="bg-neutral-900 text-neutral-500"><tr><th className="p-4">Member</th><th>Role</th><th>Status</th><th>Joined</th><th className="p-4">Actions</th></tr></thead><tbody>{filtered.map((item) => <tr className="border-t border-neutral-800" key={item.id}><td className="p-4"><p>{[item.user.first_name,item.user.last_name].filter(Boolean).join(" ") || "Unnamed user"}</p><p className="text-neutral-500">{item.user.email}</p></td><td>{canManage ? <select className={fieldClass} value={item.role} onChange={(e) => void update(item, { role: e.target.value })}>{["owner","admin","manager","member","artist"].map((value) => <option key={value}>{value}</option>)}</select> : item.role}</td><td><StatusBadge positive={item.is_active}>{item.is_active ? "Active" : "Inactive"}</StatusBadge></td><td>{new Date(item.created_at).toLocaleDateString()}</td><td className="p-4">{canManage && <button className={secondaryButtonClass} onClick={() => void update(item, { is_active: !item.is_active })}>{item.is_active ? "Deactivate" : "Activate"}</button>}</td></tr>)}</tbody></table></div>}</WorkspaceFrame>;
}

export function InvitationsPage() {
  const { activeOrganizationId, session } = useAuth();
  const path = activeOrganizationId ? `/api/organizations/${activeOrganizationId}/invitations/` : null;
  const { data, error, load } = useResource<Invitation[]>(path);
  const [email,setEmail]=useState(""); const [role,setRole]=useState("member"); const [message,setMessage]=useState(""); const [token,setToken]=useState("");
  const current = session?.memberships.find((item) => item.organization.id === activeOrganizationId);
  const canManage=current?.permissions.includes("membership.manage");
  async function create(event: FormEvent) { event.preventDefault(); if(!path)return; setMessage(""); try { const created=await apiRequest<Invitation>(path,{method:"POST",body:JSON.stringify({email,role})}); setToken(created.token ?? ""); setEmail(""); setMessage("Invitation generated. Copy the token now; it will not be shown again."); await load(); } catch(caught){setMessage(caught instanceof Error?caught.message:"Unable to create invitation.");}}
  async function revoke(item: Invitation){if(!confirm("Revoke this invitation?"))return; try{await apiRequest(`/api/invitations/${item.id}/revoke/`,{method:"POST"});setMessage("Invitation revoked.");await load();}catch(caught){setMessage(caught instanceof Error?caught.message:"Unable to revoke invitation.");}}
  return <WorkspaceFrame><PageHeader eyebrow="Workspace" title="Invitations" description="Seven-day invitations. Email delivery is not configured." />{canManage&&<form className="mt-7 grid gap-3 rounded-md border border-neutral-800 bg-neutral-900 p-5 sm:grid-cols-[1fr_12rem_auto]" onSubmit={create}><label className="text-sm text-neutral-400">Email<input className={`mt-2 ${fieldClass}`} type="email" required value={email} onChange={(e)=>setEmail(e.target.value)} /></label><label className="text-sm text-neutral-400">Role<select className={`mt-2 ${fieldClass}`} value={role} onChange={(e)=>setRole(e.target.value)}>{["owner","admin","manager","member","artist"].map((value)=><option key={value}>{value}</option>)}</select></label><button className={`self-end ${buttonClass}`}>Generate invite</button></form>}<div className="mt-4"><Notice message={error||message} error={!!error}/>{token&&<code className="mt-3 block break-all rounded-md border border-amber-800 bg-neutral-900 p-4 text-sm text-amber-300">{token}</code>}</div>{!data?<Loading/>:data.length===0?<div className="mt-7"><EmptyState title="No invitations" detail="No invitations have been created for this organization." /></div>:<div className="mt-7 grid gap-3">{data.map((item)=><div className="grid gap-3 rounded-md border border-neutral-800 bg-neutral-900 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center" key={item.id}><div><p>{item.email}</p><p className="mt-1 text-xs text-neutral-500">Created {new Date(item.created_at).toLocaleDateString()} / expires {new Date(item.expires_at).toLocaleDateString()}</p></div><StatusBadge positive={item.status==="pending"}>{item.role} / {item.status}</StatusBadge>{canManage&&item.status==="pending"&&<button className={secondaryButtonClass} onClick={()=>void revoke(item)}>Revoke</button>}</div>)}</div>}</WorkspaceFrame>;
}

export function OrganizationPage() {
  const { activeOrganizationId, session, refresh }=useAuth(); const path=activeOrganizationId?`/api/organizations/${activeOrganizationId}/`:null; const {data,error,load}=useResource<Organization>(path); const [message,setMessage]=useState(""); const membership=session?.memberships.find((item)=>item.organization.id===activeOrganizationId); const canManage=membership?.permissions.includes("organization.manage");
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!path)return;const form=new FormData(event.currentTarget);try{await apiRequest(path,{method:"PATCH",body:JSON.stringify({name:form.get("name"),slug:form.get("slug")})});setMessage("Organization updated.");await load();await refresh();}catch(caught){setMessage(caught instanceof Error?caught.message:"Unable to update organization.");}}
  return <WorkspaceFrame><PageHeader eyebrow="Workspace" title="Organization settings" description="Core organization identity and status." /><div className="mt-7 max-w-2xl"><Notice message={error||message} error={!!error}/>{data?<form key={data.updated_at} className="mt-4 grid gap-5 rounded-md border border-neutral-800 bg-neutral-900 p-6" onSubmit={save}><label className="text-sm text-neutral-400">Name<input name="name" className={`mt-2 ${fieldClass}`} disabled={!canManage} defaultValue={data.name} /></label><label className="text-sm text-neutral-400">Slug<input name="slug" className={`mt-2 ${fieldClass}`} disabled={!canManage} defaultValue={data.slug} /></label><div><StatusBadge positive={data.is_active}>{data.is_active?"Active":"Inactive"}</StatusBadge></div>{canManage&&<button className={buttonClass}>Save changes</button>}</form>:<Loading/>}</div></WorkspaceFrame>;
}

export function ProfilePage() {
  const {refresh}=useAuth();const {data,error,load}=useResource<{email:string;first_name:string;last_name:string;memberships:Member[]}>("/api/profile/");const [message,setMessage]=useState("");async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await apiRequest("/api/profile/",{method:"PATCH",body:JSON.stringify({first_name:form.get("first_name"),last_name:form.get("last_name")})});setMessage("Profile updated.");await load();await refresh();}catch(caught){setMessage(caught instanceof Error?caught.message:"Unable to update profile.");}}
  return <RouteGuard portal="dashboard"><AppShell><PageHeader eyebrow="Account" title="Profile" description="Personal details and organization memberships." /><div className="mt-7 grid gap-6 lg:grid-cols-2">{data?<form key={`${data.first_name}-${data.last_name}`} className="grid gap-5 rounded-md border border-neutral-800 bg-neutral-900 p-6" onSubmit={save}><Notice message={error||message} error={!!error}/><label className="text-sm text-neutral-400">Email<input className={`mt-2 ${fieldClass}`} disabled value={data.email}/></label><label className="text-sm text-neutral-400">First name<input name="first_name" className={`mt-2 ${fieldClass}`} defaultValue={data.first_name}/></label><label className="text-sm text-neutral-400">Last name<input name="last_name" className={`mt-2 ${fieldClass}`} defaultValue={data.last_name}/></label><button className={buttonClass}>Save profile</button></form>:<Loading/>}<div className="rounded-md border border-neutral-800 bg-neutral-900 p-6"><h2 className="font-semibold">Memberships</h2><div className="mt-4 grid gap-3">{data?.memberships.length?data.memberships.map((item)=><div className="flex justify-between border-b border-neutral-800 pb-3" key={item.id}><span>{item.organization.name}</span><span className="capitalize text-neutral-500">{item.role}</span></div>):<p className="text-sm text-neutral-500">No active memberships.</p>}</div></div></div></AppShell></RouteGuard>;
}

export function PlatformOverviewPage() {
  const {data,error}=useResource<Record<string,number>>("/api/platform/overview/");return <PlatformFrame><PageHeader eyebrow="Platform" title="Platform overview" description="Live platform identity and access totals."/><Notice message={error} error/>{data?<div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(data).map(([key,value])=><StatCard key={key} label={key.replaceAll("_"," ")} value={value}/>)}</div>:<Loading/>}</PlatformFrame>;
}

export function PlatformOrganizationsPage() {
  const {data,error}=useResource<Organization[]>("/api/platform/organizations/");const [query,setQuery]=useState("");const filtered=(data??[]).filter((item)=>`${item.name} ${item.slug}`.toLowerCase().includes(query.toLowerCase()));return <PlatformFrame><PageHeader eyebrow="Platform" title="Organizations" description="All active and inactive organizations."/><input className={`mt-6 max-w-md ${fieldClass}`} placeholder="Search organizations" value={query} onChange={(e)=>setQuery(e.target.value)}/><Notice message={error} error/>{!data?<Loading/>:filtered.length===0?<div className="mt-7"><EmptyState title="No organizations" detail="No organizations match this search."/></div>:<div className="mt-7 grid gap-3">{filtered.map((item)=><Link className="grid gap-2 rounded-md border border-neutral-800 bg-neutral-900 p-5 hover:border-neutral-600 sm:grid-cols-[1fr_auto_auto]" href={`/platform/organizations/${item.id}`} key={item.id}><div><p className="font-medium">{item.name}</p><p className="text-sm text-neutral-500">{item.slug}</p></div><span>{item.member_count} members</span><StatusBadge positive={item.is_active}>{item.is_active?"Active":"Inactive"}</StatusBadge></Link>)}</div>}</PlatformFrame>;
}

export function PlatformOrganizationDetailPage({id}:{id:string}) {
  const {data,error,load}=useResource<Organization&{members:Member[];invitations:Invitation[]}>(`/api/platform/organizations/${id}/`);async function toggle(){if(!data||!confirm(`${data.is_active?"Deactivate":"Activate"} this organization?`))return;await apiRequest(`/api/platform/organizations/${id}/`,{method:"PATCH",body:JSON.stringify({is_active:!data.is_active})});await load();}return <PlatformFrame><PageHeader eyebrow="Platform organization" title={data?.name??"Organization"} actions={data&&<button className={secondaryButtonClass} onClick={()=>void toggle()}>{data.is_active?"Deactivate":"Activate"}</button>}/><Notice message={error} error/>{data?<div className="mt-7 grid gap-6"><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Members" value={data.members.length}/><StatCard label="Invitations" value={data.invitations.length}/><StatCard label="Status" value={data.is_active?"Active":"Inactive"}/></div><section><h2 className="mb-3 font-semibold">Members</h2>{data.members.map((item)=><div className="border-t border-neutral-800 py-3 text-sm" key={item.id}>{item.user.email} <span className="text-neutral-500">/ {item.role}</span></div>)}</section></div>:<Loading/>}</PlatformFrame>;
}

export function PlatformUsersPage() {
  const {data,error}=useResource<PlatformUser[]>("/api/platform/users/");const [query,setQuery]=useState("");const filtered=(data??[]).filter((item)=>`${item.email} ${item.first_name} ${item.last_name}`.toLowerCase().includes(query.toLowerCase()));return <PlatformFrame><PageHeader eyebrow="Platform" title="Users" description="Identity status and organization membership totals."/><input className={`mt-6 max-w-md ${fieldClass}`} placeholder="Search users" value={query} onChange={(e)=>setQuery(e.target.value)}/><Notice message={error} error/>{!data?<Loading/>:<div className="mt-7 grid gap-3">{filtered.map((item)=><Link className="grid gap-2 rounded-md border border-neutral-800 bg-neutral-900 p-5 hover:border-neutral-600 sm:grid-cols-[1fr_auto_auto]" href={`/platform/users/${item.id}`} key={item.id}><div><p>{item.email}</p><p className="text-sm text-neutral-500">{[item.first_name,item.last_name].filter(Boolean).join(" ")||"No name"}</p></div><span>{item.membership_count} memberships</span><StatusBadge positive={item.is_active}>{item.is_superuser?"Superuser":item.is_active?"Active":"Inactive"}</StatusBadge></Link>)}</div>}</PlatformFrame>;
}

export function PlatformUserDetailPage({id}:{id:string}) {
  const {data,error,load}=useResource<PlatformUser>(`/api/platform/users/${id}/`);async function toggle(){if(!data||!confirm(`${data.is_active?"Deactivate":"Activate"} this user?`))return;await apiRequest(`/api/platform/users/${id}/`,{method:"PATCH",body:JSON.stringify({is_active:!data.is_active})});await load();}return <PlatformFrame><PageHeader eyebrow="Platform user" title={data?.email??"User"} actions={data&&<button className={secondaryButtonClass} onClick={()=>void toggle()}>{data.is_active?"Deactivate":"Activate"}</button>}/><Notice message={error} error/>{data?<div className="mt-7 grid gap-4 sm:grid-cols-3"><StatCard label="Status" value={data.is_active?"Active":"Inactive"}/><StatCard label="Memberships" value={data.membership_count}/><StatCard label="Last login" value={data.last_login?new Date(data.last_login).toLocaleDateString():"Never"}/></div>:<Loading/>}</PlatformFrame>;
}

export function PlatformAuditPage() {
  const {data,error}=useResource<AuditEvent[]>("/api/platform/audit/");return <PlatformFrame><PageHeader eyebrow="Platform" title="Audit" description="Read-only record of important access and administration mutations."/><Notice message={error} error/>{!data?<Loading/>:data.length===0?<div className="mt-7"><EmptyState title="No activity recorded yet" detail="Audited mutations will appear here."/></div>:<div className="mt-7 grid gap-3">{data.map((item)=><div className="rounded-md border border-neutral-800 bg-neutral-900 p-4" key={item.id}><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">{item.action}</p><time className="text-xs text-neutral-500">{new Date(item.created_at).toLocaleString()}</time></div><p className="mt-2 text-sm text-neutral-300">{item.description}</p><p className="mt-2 text-xs text-neutral-500">{item.actor??"System"} / {item.organization??"Platform"} / {item.resource_type}</p></div>)}</div>}</PlatformFrame>;
}

export function InvitePage({token}:{token:string}) {
  const {session}=useAuth();const [message,setMessage]=useState("");async function accept(){try{const membership=await apiRequest<Member>("/api/invitations/accept/",{method:"POST",body:JSON.stringify({token})});setMessage(`Invitation accepted for ${membership.organization.name}.`);}catch(caught){setMessage(caught instanceof Error?caught.message:"Unable to accept invitation.");}}return <main className="grid min-h-screen place-items-center bg-neutral-950 p-5 text-neutral-100"><section className="w-full max-w-lg rounded-md border border-neutral-800 bg-neutral-900 p-7"><p className="text-xs font-semibold uppercase text-amber-400">Evolve invitation</p><h1 className="mt-3 text-3xl font-semibold">Join organization</h1><p className="mt-3 text-sm leading-6 text-neutral-400">Sign in with the invited email address, then accept this invitation.</p><div className="mt-6"><Notice message={message} error={message.toLowerCase().includes("invalid")||message.toLowerCase().includes("expired")}/></div>{session?<button className={`mt-6 ${buttonClass}`} onClick={()=>void accept()}>Accept invitation</button>:<Link className={`mt-6 ${buttonClass}`} href={`/login?next=/invite/${encodeURIComponent(token)}`}>Sign in to continue</Link>}</section></main>;
}
