"use client";
import {useCallback,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {AppShell} from "@/components/app-shell";
import {RouteGuard} from "@/components/auth/route-guard";
import {apiRequest} from "@/lib/api/client";
import {buttonClass,fieldClass,PageHeader,secondaryButtonClass,StatusBadge} from "@/components/ui/page";
type PlatformItem={id:string;notification_type:string;organization:string|null;recipient_count:number;priority:string};
type Item={id:string;notification_type:string;category:string;title:string;message:string;priority:string;action_url:string;organization:string|null;created_at:string;read_at:string|null};
type Page={count:number;results:Item[]};
const cats=["team","bookings","call_sheets","music","marketing","documents","finance","rights","system"];
export function NotificationsPage(){const router=useRouter();const[data,setData]=useState<Item[]>([]);const[unread,setUnread]=useState(false);const[category,setCategory]=useState("");const[priority,setPriority]=useState("");const load=useCallback(()=>{const p=new URLSearchParams();if(unread)p.set("unread","true");if(category)p.set("category",category);if(priority)p.set("priority",priority);return apiRequest<Page>("/api/notifications/?"+p).then(x=>setData(x.results))},[unread,category,priority]);useEffect(()=>{void load()},[load]);async function read(item:Item,value=true){await apiRequest(`/api/notifications/${item.id}/read/`,{method:"POST",body:JSON.stringify({read:value})});if(value&&item.action_url)router.push(item.action_url);else await load()}return <RouteGuard portal="dashboard"><AppShell><PageHeader eyebrow="Activity" title="Notifications" actions={<button className={secondaryButtonClass} onClick={async()=>{await apiRequest("/api/notifications/read-all/",{method:"POST"});await load()}}>Mark all read</button>}/><div className="mt-6 grid gap-3 sm:grid-cols-3"><label className="flex items-center gap-2"><input checked={unread} onChange={e=>setUnread(e.target.checked)} type="checkbox"/>Unread only</label><select className={fieldClass} value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{cats.map(x=><option key={x}>{x}</option>)}</select><select className={fieldClass} value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priorities</option>{["low","normal","high","urgent"].map(x=><option key={x}>{x}</option>)}</select></div><div className="mt-7 grid gap-3">{data.map(item=><article className={`rounded-md border p-5 ${item.read_at?"border-neutral-800 bg-neutral-900":"border-amber-700 bg-neutral-900"}`} key={item.id}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-neutral-500">{item.organization||"Platform"} / {item.category}</p><h2 className="mt-1 font-semibold">{item.title}</h2><p className="mt-2 text-sm text-neutral-300">{item.message}</p><p className="mt-2 text-xs text-neutral-500">{new Date(item.created_at).toLocaleString()}</p></div><StatusBadge positive={!item.read_at}>{item.priority}</StatusBadge></div><div className="mt-4 flex gap-2">{item.action_url&&<button className={buttonClass} onClick={()=>void read(item)}>Open</button>}<button className={secondaryButtonClass} onClick={()=>void read(item,!item.read_at)}>{item.read_at?"Mark unread":"Mark read"}</button><button className={secondaryButtonClass} onClick={async()=>{await apiRequest(`/api/notifications/${item.id}/archive/`,{method:"POST"});await load()}}>Archive</button></div></article>)}{!data.length&&<p className="py-12 text-center text-neutral-500">No notifications</p>}</div></AppShell></RouteGuard>}
export function NotificationPreferencesPage(){const[data,setData]=useState<{category:string;in_app_enabled:boolean}[]>([]);useEffect(()=>{void apiRequest<typeof data>("/api/notification-preferences/").then(setData)},[]);async function toggle(category:string,enabled:boolean){const next=data.map(x=>x.category===category?{...x,in_app_enabled:enabled}:x);setData(next);setData(await apiRequest<typeof data>("/api/notification-preferences/",{method:"PATCH",body:JSON.stringify(next)}))}return <RouteGuard portal="dashboard"><AppShell><PageHeader eyebrow="Profile" title="In-app notifications" description="Choose which operational categories appear in your Evolve inbox."/><div className="mt-7 max-w-2xl divide-y divide-neutral-800 rounded-md border border-neutral-800">{data.map(x=><label className="flex items-center justify-between p-5" key={x.category}><span className="capitalize">{x.category.replace("_"," ")}</span><input checked={x.in_app_enabled} onChange={e=>void toggle(x.category,e.target.checked)} type="checkbox"/></label>)}</div></AppShell></RouteGuard>}
export function PlatformNotificationsPage(){const[data,setData]=useState<PlatformItem[]>([]);useEffect(()=>{void apiRequest<PlatformItem[]>("/api/platform/notifications/").then(setData)},[]);return <RouteGuard portal="platform"><AppShell><PageHeader eyebrow="Platform" title="Notification oversight" description="Aggregate delivery metadata without recipient inbox impersonation."/><div className="mt-7 grid gap-3">{data.map(x=><div className="grid gap-2 rounded-md border border-neutral-800 p-4 sm:grid-cols-4" key={x.id}><span>{x.notification_type}</span><span>{x.organization||"Platform"}</span><span>{x.recipient_count} recipients</span><span>{x.priority}</span></div>)}</div></AppShell></RouteGuard>}
