"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { RouteGuard } from "@/components/auth/route-guard";
import { apiRequest } from "@/lib/api/client";
import { buttonClass, EmptyState, fieldClass, PageHeader, secondaryButtonClass, StatCard, StatusBadge } from "@/components/ui/page";

interface Organization { id:string;name:string;slug:string;is_active:boolean;member_count:number;members?:Member[];invitations?:Invitation[] }
interface Member { id:string;role:string;is_active:boolean;organization:{name:string};user:{email:string} }
interface Invitation { id:string;email:string;role:string;status:string }
interface User { id:string;email:string;first_name:string;last_name:string;is_active:boolean;is_staff:boolean;is_superuser:boolean;membership_count:number;last_login:string|null;memberships?:Member[] }
interface Event { id:string;created_at:string;actor:string|null;organization:string|null;action:string;resource_type:string;description:string }

function useData<T>(path:string){const[data,setData]=useState<T|null>(null);const[error,setError]=useState("");const load=useCallback(async()=>{try{setData(await apiRequest<T>(path));setError("")}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load data.")}},[path]);useEffect(()=>{let cancelled=false;apiRequest<T>(path).then((next)=>{if(!cancelled)setData(next)}).catch((caught)=>{if(!cancelled)setError(caught instanceof Error?caught.message:"Unable to load data.")});return()=>{cancelled=true}},[path]);return{data,error,load}}
function Frame({children}:{children:React.ReactNode}){return <RouteGuard portal="platform"><AppShell>{children}</AppShell></RouteGuard>}
function ErrorNotice({message}:{message:string}){return message?<p className="mt-4 rounded-md border border-red-900 bg-red-950 p-3 text-sm text-red-200">{message}</p>:null}

export function OrganizationsAdminPage(){
  const{data,error,load}=useData<Organization[]>("/api/platform/organizations/");const[query,setQuery]=useState("");const[status,setStatus]=useState("");const[message,setMessage]=useState("");
  const filtered=(data??[]).filter((item)=>(!query||`${item.name} ${item.slug}`.toLowerCase().includes(query.toLowerCase()))&&(!status||String(item.is_active)===status));
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await apiRequest("/api/platform/organizations/",{method:"POST",body:JSON.stringify({name:form.get("name"),slug:form.get("slug")})});setMessage("Organization created.");event.currentTarget.reset();await load()}catch(caught){setMessage(caught instanceof Error?caught.message:"Unable to create organization.")}}
  return <Frame><PageHeader eyebrow="Platform" title="Organizations" description="Create, search, and inspect active or inactive organizations."/><form className="mt-6 grid gap-3 rounded-md border border-neutral-800 bg-neutral-900 p-4 sm:grid-cols-[1fr_1fr_auto]" onSubmit={create}><input required name="name" className={fieldClass} placeholder="Organization name"/><input required name="slug" className={fieldClass} placeholder="organization-slug"/><button className={buttonClass}>Create</button></form>{message&&<p className="mt-3 text-sm text-amber-300">{message}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2"><input className={fieldClass} placeholder="Search organizations" value={query} onChange={(e)=>setQuery(e.target.value)}/><select className={fieldClass} value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div><ErrorNotice message={error}/>{!data?<p className="py-10 text-neutral-500">Loading...</p>:filtered.length===0?<div className="mt-6"><EmptyState title="No organizations" detail="No organizations match these filters."/></div>:<div className="mt-6 grid gap-3">{filtered.map((item)=><Link className="grid gap-3 rounded-md border border-neutral-800 bg-neutral-900 p-5 sm:grid-cols-[1fr_auto_auto]" href={`/platform/organizations/${item.id}`} key={item.id}><div><p>{item.name}</p><p className="text-sm text-neutral-500">{item.slug}</p></div><span>{item.member_count} members</span><StatusBadge positive={item.is_active}>{item.is_active?"Active":"Inactive"}</StatusBadge></Link>)}</div>}</Frame>
}

export function OrganizationAdminDetailPage({id}:{id:string}){
  const{data,error,load}=useData<Organization>(`/api/platform/organizations/${id}/`);const[message,setMessage]=useState("");
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!data)return;const form=new FormData(event.currentTarget);try{await apiRequest(`/api/platform/organizations/${id}/`,{method:"PATCH",body:JSON.stringify({name:form.get("name"),slug:form.get("slug")})});setMessage("Organization updated.");await load()}catch(caught){setMessage(caught instanceof Error?caught.message:"Unable to update.")}}
  async function toggle(){if(!data||!confirm(`${data.is_active?"Deactivate":"Activate"} this organization?`))return;await apiRequest(`/api/platform/organizations/${id}/`,{method:"PATCH",body:JSON.stringify({is_active:!data.is_active})});await load()}
  return <Frame><PageHeader eyebrow="Platform organization" title={data?.name??"Organization"} actions={data&&<button className={secondaryButtonClass} onClick={()=>void toggle()}>{data.is_active?"Deactivate":"Activate"}</button>}/><ErrorNotice message={error}/>{message&&<p className="mt-4 text-sm text-amber-300">{message}</p>}{data?<div className="mt-7 grid gap-7"><form key={data.name+data.slug} className="grid gap-3 rounded-md border border-neutral-800 bg-neutral-900 p-5 sm:grid-cols-[1fr_1fr_auto]" onSubmit={save}><input name="name" className={fieldClass} defaultValue={data.name}/><input name="slug" className={fieldClass} defaultValue={data.slug}/><button className={buttonClass}>Save</button></form><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Members" value={data.members?.length??0}/><StatCard label="Invitations" value={data.invitations?.length??0}/><StatCard label="Status" value={data.is_active?"Active":"Inactive"}/></div><section><h2 className="font-semibold">Members</h2>{data.members?.length?data.members.map((item)=><div className="mt-3 flex justify-between border-t border-neutral-800 pt-3 text-sm" key={item.id}><span>{item.user.email}</span><span className="text-neutral-500">{item.role}</span></div>):<p className="mt-3 text-sm text-neutral-500">No memberships.</p>}</section><section><h2 className="font-semibold">Invitations</h2>{data.invitations?.length?data.invitations.map((item)=><div className="mt-3 flex justify-between border-t border-neutral-800 pt-3 text-sm" key={item.id}><span>{item.email}</span><span className="text-neutral-500">{item.role} / {item.status}</span></div>):<p className="mt-3 text-sm text-neutral-500">No invitations.</p>}</section></div>:<p className="py-10 text-neutral-500">Loading...</p>}</Frame>
}

export function UsersAdminPage(){const{data,error}=useData<User[]>("/api/platform/users/");const[query,setQuery]=useState("");const[status,setStatus]=useState("");const filtered=(data??[]).filter((item)=>(!query||`${item.email} ${item.first_name} ${item.last_name}`.toLowerCase().includes(query.toLowerCase()))&&(!status||String(item.is_active)===status));return <Frame><PageHeader eyebrow="Platform" title="Users" description="Search identities and inspect access."/><div className="mt-6 grid gap-3 sm:grid-cols-2"><input className={fieldClass} placeholder="Search users" value={query} onChange={(e)=>setQuery(e.target.value)}/><select className={fieldClass} value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div><ErrorNotice message={error}/><div className="mt-6 grid gap-3">{filtered.map((item)=><Link className="grid gap-3 rounded-md border border-neutral-800 bg-neutral-900 p-5 sm:grid-cols-[1fr_auto_auto]" href={`/platform/users/${item.id}`} key={item.id}><span>{item.email}</span><span>{item.membership_count} memberships</span><StatusBadge positive={item.is_active}>{item.is_superuser?"Superuser":item.is_active?"Active":"Inactive"}</StatusBadge></Link>)}</div></Frame>}

export function UserAdminDetailPage({id}:{id:string}){const{data,error,load}=useData<User>(`/api/platform/users/${id}/`);async function toggle(){if(!data||!confirm(`${data.is_active?"Deactivate":"Activate"} this user?`))return;await apiRequest(`/api/platform/users/${id}/`,{method:"PATCH",body:JSON.stringify({is_active:!data.is_active})});await load()}return <Frame><PageHeader eyebrow="Platform user" title={data?.email??"User"} actions={data&&<button className={secondaryButtonClass} onClick={()=>void toggle()}>{data.is_active?"Deactivate":"Activate"}</button>}/><ErrorNotice message={error}/>{data?<div className="mt-7 grid gap-7"><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Status" value={data.is_active?"Active":"Inactive"}/><StatCard label="Memberships" value={data.membership_count}/><StatCard label="Last login" value={data.last_login?new Date(data.last_login).toLocaleDateString():"Never"}/></div><section><h2 className="font-semibold">Organization memberships</h2>{data.memberships?.length?data.memberships.map((item)=><div className="mt-3 flex justify-between border-t border-neutral-800 pt-3 text-sm" key={item.id}><span>{item.organization.name}</span><span className="text-neutral-500">{item.role} / {item.is_active?"active":"inactive"}</span></div>):<p className="mt-3 text-sm text-neutral-500">No memberships.</p>}</section></div>:<p className="py-10 text-neutral-500">Loading...</p>}</Frame>}

export function AuditAdminPage(){const{data,error}=useData<Event[]>("/api/platform/audit/");const[query,setQuery]=useState("");const filtered=(data??[]).filter((item)=>`${item.action} ${item.actor} ${item.organization} ${item.description}`.toLowerCase().includes(query.toLowerCase()));return <Frame><PageHeader eyebrow="Platform" title="Audit" description="Read-only important mutation history."/><input className={`mt-6 max-w-lg ${fieldClass}`} placeholder="Filter actor, organization, action, or description" value={query} onChange={(e)=>setQuery(e.target.value)}/><ErrorNotice message={error}/>{!data?<p className="py-10 text-neutral-500">Loading...</p>:filtered.length===0?<div className="mt-6"><EmptyState title="No activity recorded yet" detail="No audit events match this filter."/></div>:<div className="mt-6 grid gap-3">{filtered.map((item)=><div className="rounded-md border border-neutral-800 bg-neutral-900 p-4" key={item.id}><div className="flex flex-wrap justify-between gap-2"><p>{item.action}</p><time className="text-xs text-neutral-500">{new Date(item.created_at).toLocaleString()}</time></div><p className="mt-2 text-sm text-neutral-300">{item.description}</p><p className="mt-2 text-xs text-neutral-500">{item.actor??"System"} / {item.organization??"Platform"} / {item.resource_type}</p></div>)}</div>}</Frame>}
