"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { useAuth } from "@/components/auth/auth-provider";
import { RouteGuard } from "@/components/auth/route-guard";
import { apiRequest } from "@/lib/api/client";
import { buttonClass, fieldClass, PageHeader, secondaryButtonClass, StatusBadge } from "@/components/ui/page";

type ShowDay = { id: string; reference: string; title: string; event_date: string; timezone: string; venue_name_snapshot: string; city_snapshot: string; artist: { stage_name: string }; readiness: Record<string, { status: string; href: string }>; team?: { id: string; member?: { name: string; email: string }; responsibility: string }[]; contacts?: { id: string; snapshot_name: string; snapshot_email: string; responsibility: string }[] };
type Track = { id: string; title: string; artist: string; version_title: string; isrc: string; genre: string; language: string; status: string };
type Release = { id: string; title: string; artist: string; status: string; planned_release_date: string | null; upc_ean: string; artwork_url: string; public_url: string; presave_url: string; track_count: number };

function Frame({ children }: { children: React.ReactNode }) { return <RouteGuard portal="workspace"><AppShell organizationScoped>{children}</AppShell></RouteGuard>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-neutral-800 bg-neutral-950 p-5"><h2 className="font-semibold">{title}</h2>{children}</section>; }

export function BookingShowDayPage({ id }: { id: string }) {
  const [booking, setBooking] = useState<ShowDay | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { apiRequest<ShowDay>(`/api/bookings/${id}/`).then(setBooking).catch(() => setError("Unable to load show-day operations.")); }, [id]);
  if (!booking) return <Frame><main className="p-4 sm:p-8"><p>{error || "Loading show day…"}</p></main></Frame>;
  return <Frame><main className="p-4 sm:p-8"><PageHeader eyebrow="Show day" title={`${booking.artist.stage_name} · ${booking.title}`} description={`${booking.reference} · ${booking.event_date} · ${booking.timezone}`} actions={<div className="flex flex-wrap gap-2"><Link className={buttonClass} href={`/workspace/bookings/${id}/call-sheet`}>Open Call Sheet</Link><Link className={secondaryButtonClass} href={`/workspace/bookings/${id}`}>Booking detail</Link></div>} /><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Section title="Venue"><p className="mt-2 text-sm">{booking.venue_name_snapshot || "Venue to be confirmed"}</p><p className="text-sm text-neutral-500">{booking.city_snapshot || "City to be confirmed"}</p></Section><Section title="Readiness"><div className="mt-2 grid gap-2">{Object.entries(booking.readiness).map(([key, item]) => <Link className="flex justify-between text-sm" href={item.href} key={key}><span>{key.replaceAll("_", " ")}</span><StatusBadge positive={item.status !== "missing" && item.status !== "blocked"}>{item.status}</StatusBadge></Link>)}</div></Section><Section title="Team"><div className="mt-2 space-y-2 text-sm">{booking.team?.length ? booking.team.map((item) => <p key={item.id}>{item.member?.name || item.member?.email} <span className="text-neutral-500">· {item.responsibility}</span></p>) : <p className="text-neutral-500">No team assigned.</p>}</div></Section><Section title="Key contacts"><div className="mt-2 space-y-2 text-sm">{booking.contacts?.length ? booking.contacts.map((item) => <p key={item.id}>{item.snapshot_name} <span className="text-neutral-500">· {item.responsibility}</span></p>) : <p className="text-neutral-500">No contacts assigned.</p>}</div></Section></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><Section title="Operations"><div className="mt-3 grid gap-2"><Link className={secondaryButtonClass} href={`/workspace/production/new?booking=${id}`}>Open Production</Link><Link className={secondaryButtonClass} href={`/workspace/travel/new?booking=${id}`}>Open Travel</Link><Link className={secondaryButtonClass} href="/workspace/tasks">Open Tasks</Link></div></Section><Section title="Documents"><p className="mt-2 text-sm text-neutral-500">Open the Booking detail to review linked operational documents.</p><Link className="mt-3 inline-flex text-sm text-amber-300" href={`/workspace/bookings/${id}`}>Review documents →</Link></Section><Section title="Show-day safety"><p className="mt-2 text-sm text-neutral-500">Published Call Sheet data remains authoritative. No sensitive operational data is cached by the PWA.</p></Section></div></main></Frame>;
}

export function MusicMetadataPage() {
  const { activeOrganizationId } = useAuth();
  const [tracks, setTracks] = useState<Track[]>([]);
  const [filter, setFilter] = useState("all");
  useEffect(() => { if (activeOrganizationId) void apiRequest<Track[]>(`/api/music/tracks/?organization_id=${activeOrganizationId}`).then(setTracks); }, [activeOrganizationId]);
  const rows = useMemo(() => tracks.filter((track) => filter === "all" || (filter === "missing-isrc" ? !track.isrc : !track.genre || !track.language)), [filter, tracks]);
  return <Frame><main className="p-4 sm:p-8"><PageHeader eyebrow="Music" title="Metadata workspace" description="Review real catalog metadata and resolve incomplete fields before release preparation." actions={<Link className={secondaryButtonClass} href="/workspace/music/tracks/new">New track</Link>} /><div className="mt-6 flex flex-wrap gap-2"><select className={fieldClass} value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All tracks</option><option value="missing-isrc">Missing ISRC</option><option value="incomplete">Incomplete genre/language</option></select><Link className={secondaryButtonClass} href="/workspace/music">Music overview</Link></div><div className="mt-6 grid gap-3">{rows.map((track) => <Link className="grid gap-2 rounded-xl border border-neutral-800 bg-neutral-950 p-4 sm:grid-cols-[minmax(0,1.3fr)_1fr_1fr_auto] sm:items-center" href={`/workspace/music/tracks/${track.id}`} key={track.id}><span><span className="block font-medium">{track.title}</span><span className="block text-sm text-neutral-500">{track.artist} · {track.version_title || "Original"}</span></span><span className="text-sm">{track.isrc || <span className="text-amber-300">ISRC missing</span>}</span><span className="text-sm text-neutral-500">{track.genre || "Genre missing"} · {track.language || "Language missing"}</span><StatusBadge positive={track.status === "active"}>{track.status}</StatusBadge></Link>)}{!rows.length && <p className="rounded-xl border border-dashed border-neutral-700 p-8 text-sm text-neutral-500">No tracks match this metadata view.</p>}</div></main></Frame>;
}

export function MusicDistributionPage() {
  const { activeOrganizationId } = useAuth();
  const [releases, setReleases] = useState<Release[]>([]);
  useEffect(() => { if (activeOrganizationId) void apiRequest<Release[]>(`/api/music/releases/?organization_id=${activeOrganizationId}`).then(setReleases); }, [activeOrganizationId]);
  return <Frame><main className="p-4 sm:p-8"><PageHeader eyebrow="Music" title="Distribution readiness" description="A conservative operational view of existing release metadata. Evolve does not pretend to deliver directly to DSPs." actions={<Link className={secondaryButtonClass} href="/workspace/music/releases">Releases</Link>} /><div className="mt-6 grid gap-3">{releases.map((release) => { const missing = [!release.track_count && "tracks", !release.upc_ean && "UPC/EAN", !release.artwork_url && "artwork", !release.planned_release_date && "release date"].filter(Boolean) as string[]; return <Link className="grid gap-3 rounded-xl border border-neutral-800 bg-neutral-950 p-4 md:grid-cols-[minmax(0,1.4fr)_1fr_1fr_auto] md:items-center" href={`/workspace/music/releases/${release.id}`} key={release.id}><span><span className="block font-medium">{release.title}</span><span className="block text-sm text-neutral-500">{release.artist}</span></span><span className="text-sm">{release.track_count} tracks · {release.upc_ean || "No UPC/EAN"}</span><span className="text-sm text-neutral-500">{release.planned_release_date || "Release date TBC"}</span><StatusBadge positive={!missing.length}>{missing.length ? `Needs attention: ${missing.join(", ")}` : release.status}</StatusBadge></Link>})}{!releases.length && <p className="rounded-xl border border-dashed border-neutral-700 p-8 text-sm text-neutral-500">No releases available.</p>}</div></main></Frame>;
}
