# Generated by Django 5.2.5 on 2026-08-24 13:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stage_name", models.CharField(max_length=180)),
                ("legal_name", models.CharField(blank=True, max_length=180)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("biography", models.TextField(blank=True, max_length=10000)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("management_email", models.EmailField(blank=True, max_length=254)),
                ("booking_email", models.EmailField(blank=True, max_length=254)),
                ("profile_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artists",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("stage_name",),
            },
        ),
        migrations.CreateModel(
            name="ArtistPortalLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("artist", "Artist"),
                            ("assistant", "Assistant"),
                            ("co_manager", "Co-manager"),
                        ],
                        default="artist",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_links",
                        to="artists.artist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artist_portal_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ArtistTeamAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "responsibility",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("booking", "Booking"),
                            ("marketing", "Marketing"),
                            ("finance", "Finance"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_assignments",
                        to="artists.artist",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artist_assignments",
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "responsibility", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(
                fields=["organization", "status"], name="artists_art_organiz_156052_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="artist",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"),
                name="unique_artist_slug_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="artistportallink",
            constraint=models.UniqueConstraint(
                fields=("artist", "user"), name="unique_artist_portal_user_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="artistteamassignment",
            constraint=models.UniqueConstraint(
                fields=("artist", "membership"),
                name="unique_artist_membership_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="artistteamassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("artist",),
                name="one_active_primary_assignment_per_artist",
            ),
        ),
    ]
