# Generated by Django 5.2.5 on 2026-08-25 16:31

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import travel.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("bookings", "0001_initial"),
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelItinerary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Johannesburg",
                        max_length=64,
                        validators=[travel.models.validate_timezone],
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True, max_length=5000)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="travel_itineraries",
                        to="artists.artist",
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="travel_itinerary",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_itineraries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="travel_itineraries",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at", "title"),
            },
        ),
        migrations.CreateModel(
            name="ItineraryTraveller",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=301)),
                (
                    "traveller_type",
                    models.CharField(
                        choices=[
                            ("artist", "Artist"),
                            ("team", "Team"),
                            ("guest", "Guest"),
                            ("crew", "Crew"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("phone_snapshot", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True, max_length=3000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itinerary_traveller_entries",
                        to="artists.artist",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itinerary_traveller_entries",
                        to="organizations.membership",
                    ),
                ),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="travellers",
                        to="travel.travelitinerary",
                    ),
                ),
            ],
            options={
                "ordering": ("traveller_type", "display_name"),
            },
        ),
        migrations.CreateModel(
            name="AccommodationStay",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("property_name", models.CharField(max_length=220)),
                ("address", models.CharField(blank=True, max_length=520)),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=100)),
                (
                    "timezone",
                    models.CharField(max_length=64, validators=[travel.models.validate_timezone]),
                ),
                ("check_in_at", models.DateTimeField()),
                ("check_out_at", models.DateTimeField()),
                ("confirmation_reference", models.CharField(blank=True, max_length=220)),
                ("contact_name", models.CharField(blank=True, max_length=220)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True, max_length=3000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked in"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stays",
                        to="travel.travelitinerary",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "check_in_at"),
            },
        ),
        migrations.CreateModel(
            name="TravelSegment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "segment_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("rail", "Rail"),
                            ("ground", "Ground"),
                            ("ferry", "Ferry"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=220)),
                ("service_number", models.CharField(blank=True, max_length=80)),
                ("confirmation_reference", models.CharField(blank=True, max_length=220)),
                ("departure_location", models.CharField(max_length=220)),
                ("arrival_location", models.CharField(max_length=220)),
                ("departure_at", models.DateTimeField()),
                ("arrival_at", models.DateTimeField(blank=True, null=True)),
                (
                    "departure_timezone",
                    models.CharField(max_length=64, validators=[travel.models.validate_timezone]),
                ),
                (
                    "arrival_timezone",
                    models.CharField(max_length=64, validators=[travel.models.validate_timezone]),
                ),
                ("terminal_or_platform", models.CharField(blank=True, max_length=120)),
                ("seat_or_vehicle_info", models.CharField(blank=True, max_length=220)),
                ("airline", models.CharField(blank=True, max_length=180)),
                ("flight_number", models.CharField(blank=True, max_length=40)),
                (
                    "departure_airport_code",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three-letter uppercase airport code."
                            )
                        ],
                    ),
                ),
                (
                    "arrival_airport_code",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three-letter uppercase airport code."
                            )
                        ],
                    ),
                ),
                ("driver_name", models.CharField(blank=True, max_length=220)),
                ("driver_phone", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True, max_length=3000)),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segments",
                        to="travel.travelitinerary",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "departure_at"),
            },
        ),
        migrations.CreateModel(
            name="TravelSegmentTraveller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("seat", models.CharField(blank=True, max_length=80)),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traveller_assignments",
                        to="travel.travelsegment",
                    ),
                ),
                (
                    "traveller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_assignments",
                        to="travel.itinerarytraveller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccommodationRoomAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("room_label", models.CharField(blank=True, max_length=120)),
                ("room_type", models.CharField(blank=True, max_length=120)),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_assignments",
                        to="travel.accommodationstay",
                    ),
                ),
                (
                    "traveller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="room_assignments",
                        to="travel.itinerarytraveller",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stay", "traveller"), name="unique_stay_traveller_room"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="travelitinerary",
            index=models.Index(
                fields=["organization", "status", "starts_at"],
                name="travel_trav_organiz_4ef4c6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerarytraveller",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artist__isnull", False),
                    ("membership__isnull", False),
                    models.Q(("display_name", ""), _negated=True),
                    _connector="OR",
                ),
                name="travel_traveller_has_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="accommodationstay",
            constraint=models.UniqueConstraint(
                fields=("itinerary", "sequence"), name="unique_accommodation_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="travelsegment",
            index=models.Index(
                fields=["itinerary", "departure_at"], name="travel_trav_itinera_55675c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="travelsegment",
            constraint=models.UniqueConstraint(
                fields=("itinerary", "sequence"), name="unique_travel_segment_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="travelsegmenttraveller",
            constraint=models.UniqueConstraint(
                fields=("segment", "traveller"), name="unique_segment_traveller"
            ),
        ),
    ]
