# Generated by Django 5.2.5 on 2026-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='schema_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
