# Generated by Django 5.2.5 on 2026-09-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0004_workspace_board_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="context_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("task", "Task"),
                    ("booking", "Booking"),
                    ("campaign", "Campaign"),
                    ("production", "Production"),
                ],
                max_length=20,
            ),
        ),
    ]
