# Generated by Django 5.2.5 on 2026-09-24 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('workspace', '0007_comment_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailbox_access', to='workspace.messagingconnector')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox_access_granted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailbox_access', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailbox_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'user', 'is_active'], name='workspace_m_organiz_9364ab_idx')],
                'constraints': [models.UniqueConstraint(fields=('connector', 'user'), name='unique_mailbox_access_user_connector')],
            },
        ),
        migrations.CreateModel(
            name='MailboxReply',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_address', models.EmailField(max_length=254)),
                ('recipient_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=220)),
                ('body_text', models.TextField(max_length=10000)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=16)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='workspace.inboundmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['message', 'created_at'], name='workspace_m_message_fa344f_idx')],
            },
        ),
    ]
