# Generated by Django 5.2.5 on 2026-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_mailbox_composition_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxsentmessage',
            name='tagged_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
