# Generated by Django 5.2.5 on 2026-09-27 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('documents', '0016_alter_document_document_type'),
        ('organizations', '0004_membership_permission_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('template_key', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to send'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('partially_signed', 'Partially signed'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=24)),
                ('provider', models.CharField(default='opensign', max_length=32)),
                ('provider_document_id', models.CharField(blank=True, max_length=220)),
                ('signing_url', models.URLField(blank=True, max_length=1000)),
                ('completed_document_url', models.URLField(blank=True, max_length=1000)),
                ('signers', models.JSONField(default=list)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_requests_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_requests', to='organizations.organization')),
                ('source_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signing_requests', to='contracts.contract')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signing_requests', to='documents.document')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SigningEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_event_id', models.CharField(blank=True, max_length=220)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to send'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('partially_signed', 'Partially signed'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=24)),
                ('payload_digest', models.CharField(max_length=64)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='signing.signingrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='signingrequest',
            index=models.Index(fields=['organization', 'status'], name='signing_sig_organiz_28ae5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='signingevent',
            constraint=models.UniqueConstraint(fields=('request', 'provider_event_id'), name='signing_unique_provider_event'),
        ),
    ]
