# Generated by Django 5.2.5 on 2026-08-24 17:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("music", "0001_initial"),
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "objective",
                    models.CharField(
                        choices=[
                            ("awareness", "Awareness"),
                            ("pre_save", "Pre-save"),
                            ("release_launch", "Release launch"),
                            ("audience_growth", "Audience growth"),
                            ("engagement", "Engagement"),
                            ("streaming", "Streaming"),
                            ("press", "Press"),
                            ("live", "Live"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_audience", models.CharField(blank=True, max_length=500)),
                ("summary", models.TextField(blank=True, max_length=10000)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="artists.artist",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_campaigns",
                        to="organizations.membership",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="music.release",
                    ),
                ),
            ],
            options={
                "ordering": ("-start_date", "name"),
            },
        ),
        migrations.CreateModel(
            name="CampaignChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("x", "X"),
                            ("facebook", "Facebook"),
                            ("spotify", "Spotify"),
                            ("apple_music", "Apple Music"),
                            ("deezer", "Deezer"),
                            ("email", "Email"),
                            ("press", "Press"),
                            ("radio", "Radio"),
                            ("playlisting", "Playlisting"),
                            ("influencers", "Influencers"),
                            ("ooh", "Out of home"),
                            ("live", "Live"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=1000)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="channels",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "channel"),
            },
        ),
        migrations.CreateModel(
            name="Rollout",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=10000)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollouts",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollouts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollouts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_rollouts",
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "ordering": ("start_date", "name"),
            },
        ),
        migrations.CreateModel(
            name="RolloutMilestone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True, max_length=5000)),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("blocked", "Blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "owner_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_rollout_milestones",
                        to="organizations.membership",
                    ),
                ),
                (
                    "rollout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milestones",
                        to="campaigns.rollout",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "target_date", "title"),
            },
        ),
        migrations.CreateModel(
            name="RolloutTask",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True, max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To do"),
                            ("in_progress", "In progress"),
                            ("blocked", "Blocked"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "assigned_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_rollout_tasks",
                        to="organizations.membership",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_rollout_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="campaigns.rolloutmilestone",
                    ),
                ),
                (
                    "rollout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="campaigns.rollout",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "due_date", "title"),
            },
        ),
        migrations.CreateModel(
            name="RolloutTaskDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dependents",
                        to="campaigns.rollouttask",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dependencies",
                        to="campaigns.rollouttask",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_campaign_slug_per_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignchannel",
            constraint=models.UniqueConstraint(
                fields=("campaign", "channel"), name="unique_channel_per_campaign"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignchannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("campaign",),
                name="one_primary_channel_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolloutmilestone",
            constraint=models.UniqueConstraint(
                fields=("rollout", "sequence"), name="unique_milestone_sequence_per_rollout"
            ),
        ),
        migrations.AddConstraint(
            model_name="rollouttaskdependency",
            constraint=models.UniqueConstraint(
                fields=("task", "depends_on"), name="unique_rollout_task_dependency"
            ),
        ),
        migrations.AddConstraint(
            model_name="rollouttaskdependency",
            constraint=models.CheckConstraint(
                condition=models.Q(("task", models.F("depends_on")), _negated=True),
                name="task_cannot_depend_on_itself",
            ),
        ),
    ]
