# Generated by Django 5.2.5 on 2026-08-31 07:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignResponsibility",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("phase", models.CharField(max_length=80)),
                (
                    "role",
                    models.CharField(
                        choices=[("lead", "Lead"), ("support", "Support")], max_length=16
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsibilities",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_responsibilities",
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "ordering": ("phase", "role", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "membership", "phase", "role"),
                        name="unique_campaign_phase_responsibility",
                    )
                ],
            },
        ),
    ]
