# Generated by Django 5.2.5 on 2026-09-28 08:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('organizations', '0004_membership_permission_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInvoiceSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under review'), ('approved', 'Approved'), ('settled', 'Settled'), ('rejected', 'Rejected')], default='submitted', max_length=16)),
                ('invoice_date', models.DateField()),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a three-letter uppercase currency code.')])),
                ('line_items', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_submissions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_invoice_submissions', to='organizations.organization')),
                ('settled_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_submissions', to='finance.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(blank=True, max_length=220)),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('tax_number', models.CharField(blank=True, max_length=120)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_address', models.TextField(blank=True, max_length=2000)),
                ('payment_terms', models.CharField(default='Due within 30 days', max_length=120)),
                ('invoice_prefix', models.CharField(default='INV', max_length=12)),
                ('quote_prefix', models.CharField(default='QUO', max_length=12)),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('next_quote_number', models.PositiveIntegerField(default=1)),
                ('default_currency', models.CharField(default='ZAR', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a three-letter uppercase currency code.')])),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finance_profile', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=16)),
                ('billed_to_name', models.CharField(max_length=220)),
                ('billed_to_email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a three-letter uppercase currency code.')])),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=16)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='finance.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
