# Generated by Django 5.2.5 on 2026-08-24 14:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promoter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("company_name", models.CharField(blank=True, max_length=180)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=500)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("province", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=30)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True, max_length=5000)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promoters",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PromoterContact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "responsibility",
                    models.CharField(
                        choices=[
                            ("promoter", "Promoter"),
                            ("production", "Production"),
                            ("finance", "Finance"),
                            ("hospitality", "Hospitality"),
                            ("marketing", "Marketing"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promoter_links",
                        to="contacts.contact",
                    ),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_links",
                        to="promoters.promoter",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "responsibility", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="promoter",
            index=models.Index(
                fields=["organization", "status"], name="promoters_p_organiz_e1b8d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="promoter",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_promoter_slug_per_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotercontact",
            constraint=models.UniqueConstraint(
                fields=("promoter", "contact"), name="unique_promoter_contact_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotercontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("promoter", "responsibility"),
                name="one_primary_promoter_contact_per_role",
            ),
        ),
    ]
