# Generated by Django 5.2.5 on 2026-08-24 19:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("bookings", "0001_initial"),
        ("callsheets", "0001_initial"),
        ("campaigns", "0001_initial"),
        ("music", "0001_initial"),
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Contract"),
                            ("call_sheet", "Call sheet"),
                            ("rider", "Rider"),
                            ("press", "Press"),
                            ("artwork", "Artwork"),
                            ("music", "Music"),
                            ("invoice", "Invoice"),
                            ("receipt", "Receipt"),
                            ("travel", "Travel"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=5000)),
                ("storage_key", models.CharField(blank=True, editable=False, max_length=500)),
                ("external_url", models.URLField(blank=True, max_length=1000)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, editable=False, max_length=64)),
                ("version_number", models.PositiveIntegerField(default=1)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("restricted", "Restricted"),
                            ("artist", "Artist"),
                        ],
                        default="organization",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="newer_versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "title"),
            },
        ),
        migrations.CreateModel(
            name="DocumentLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="artists.artist",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="bookings.booking",
                    ),
                ),
                (
                    "call_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="callsheets.callsheet",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="documents.document",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="music.release",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "status", "document_type"],
                name="documents_d_organiz_6dd62a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent_document__isnull", False)),
                fields=("parent_document", "version_number"),
                name="unique_document_lineage_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("artist__isnull", False),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", True),
                        ("release__isnull", True),
                        ("campaign__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", False),
                        ("call_sheet__isnull", True),
                        ("release__isnull", True),
                        ("campaign__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", False),
                        ("release__isnull", True),
                        ("campaign__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", True),
                        ("release__isnull", False),
                        ("campaign__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", True),
                        ("release__isnull", True),
                        ("campaign__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="document_link_exactly_one_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("artist__isnull", False)),
                fields=("document", "artist"),
                name="unique_document_artist_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("booking__isnull", False)),
                fields=("document", "booking"),
                name="unique_document_booking_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("call_sheet__isnull", False)),
                fields=("document", "call_sheet"),
                name="unique_document_callsheet_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("release__isnull", False)),
                fields=("document", "release"),
                name="unique_document_release_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("campaign__isnull", False)),
                fields=("document", "campaign"),
                name="unique_document_campaign_link",
            ),
        ),
    ]
