# Generated by Django 5.2.5 on 2026-08-25 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentlink",
            name="document_link_exactly_one_entity",
        ),
        migrations.RemoveConstraint(
            model_name="documentlink",
            name="unique_document_callsheet_link",
        ),
    ]
