# Generated by Django 5.2.5 on 2026-08-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
        ("bookings", "0001_initial"),
        ("callsheets", "0001_initial"),
        ("campaigns", "0001_initial"),
        ("documents", "0002_remove_documentlink_document_link_exactly_one_entity_and_more"),
        ("music", "0001_initial"),
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentlink",
            name="accommodation_stay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_links",
                to="travel.accommodationstay",
            ),
        ),
        migrations.AddField(
            model_name="documentlink",
            name="travel_itinerary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_links",
                to="travel.travelitinerary",
            ),
        ),
        migrations.AddField(
            model_name="documentlink",
            name="travel_segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_links",
                to="travel.travelsegment",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("artist__isnull", False),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", True),
                        ("release__isnull", True),
                        ("campaign__isnull", True),
                        ("travel_itinerary__isnull", True),
                        ("travel_segment__isnull", True),
                        ("accommodation_stay__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", False),
                        ("call_sheet__isnull", True),
                        ("release__isnull", True),
                        ("campaign__isnull", True),
                        ("travel_itinerary__isnull", True),
                        ("travel_segment__isnull", True),
                        ("accommodation_stay__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", False),
                        ("release__isnull", True),
                        ("campaign__isnull", True),
                        ("travel_itinerary__isnull", True),
                        ("travel_segment__isnull", True),
                        ("accommodation_stay__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", True),
                        ("release__isnull", False),
                        ("campaign__isnull", True),
                        ("travel_itinerary__isnull", True),
                        ("travel_segment__isnull", True),
                        ("accommodation_stay__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", True),
                        ("release__isnull", True),
                        ("campaign__isnull", False),
                        ("travel_itinerary__isnull", True),
                        ("travel_segment__isnull", True),
                        ("accommodation_stay__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", True),
                        ("release__isnull", True),
                        ("campaign__isnull", True),
                        ("travel_itinerary__isnull", False),
                        ("travel_segment__isnull", True),
                        ("accommodation_stay__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", True),
                        ("release__isnull", True),
                        ("campaign__isnull", True),
                        ("travel_itinerary__isnull", True),
                        ("travel_segment__isnull", False),
                        ("accommodation_stay__isnull", True),
                    ),
                    models.Q(
                        ("artist__isnull", True),
                        ("booking__isnull", True),
                        ("call_sheet__isnull", True),
                        ("release__isnull", True),
                        ("campaign__isnull", True),
                        ("travel_itinerary__isnull", True),
                        ("travel_segment__isnull", True),
                        ("accommodation_stay__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="document_link_exactly_one_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("call_sheet__isnull", False)),
                fields=("document", "call_sheet"),
                name="unique_document_call_sheet_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("travel_itinerary__isnull", False)),
                fields=("document", "travel_itinerary"),
                name="unique_document_travel_itinerary_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("travel_segment__isnull", False)),
                fields=("document", "travel_segment"),
                name="unique_document_travel_segment_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("accommodation_stay__isnull", False)),
                fields=("document", "accommodation_stay"),
                name="unique_document_accommodation_stay_link",
            ),
        ),
    ]
