# Generated by Django 5.2.5 on 2026-08-25 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_documentlink_accommodation_stay_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentlink",
            name="document_link_exactly_one_entity",
        ),
    ]
