# Generated by Django 5.2.5 on 2026-08-28 12:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_documentlink_production_advance_and_more"),
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="rendered_content",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="document",
            name="template_version",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=220)),
                ("key", models.SlugField(max_length=120)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmation", "Booking confirmation"),
                            ("contract_summary", "Contract summary"),
                            ("invoice_cover", "Invoice cover"),
                            ("travel_itinerary", "Travel itinerary"),
                            ("production_advance", "Production advance"),
                            ("general", "General"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_templates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_documents",
                to="documents.documenttemplate",
            ),
        ),
        migrations.CreateModel(
            name="DocumentTemplateSection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.SlugField(max_length=120)),
                ("title", models.CharField(max_length=220)),
                ("body", models.TextField(max_length=10000)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="documents.documenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "key"), name="unique_document_template_key_per_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", True)),
                fields=("key",),
                name="unique_platform_document_template_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplatesection",
            constraint=models.UniqueConstraint(
                fields=("template", "key"), name="unique_section_key_per_template"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplatesection",
            constraint=models.UniqueConstraint(
                fields=("template", "sequence"), name="unique_section_sequence_per_template"
            ),
        ),
    ]
