# Generated by Django 5.2.5 on 2026-08-31 13:19

import django.db.models.deletion
from django.db import migrations, models


def classify_existing_documents(apps, schema_editor):
    document = apps.get_model("documents", "Document")
    document.objects.exclude(rendered_content="").update(source_type="generated")


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_document_rendered_content_document_template_version_and_more"),
        ("integrations", "0002_alter_emailconnector_secret_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="detected_content_type",
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name="document",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("external", "External reference"),
                    ("stored", "Stored file"),
                    ("generated", "Generated"),
                ],
                default="external",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="storage_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stored_documents",
                to="integrations.storageprovider",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="storage_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not applicable"),
                    ("available", "Available"),
                    ("failed", "Failed"),
                    ("archived", "Archived"),
                ],
                default="not_applicable",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(classify_existing_documents, migrations.RunPython.noop),
    ]
