# Generated by Django 5.2.5 on 2026-09-12 22:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_document_detected_content_type_document_source_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRevision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("content_json", models.JSONField(default=dict)),
                ("change_summary", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_revisions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="office_revisions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ("-revision_number",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "revision_number"),
                        name="unique_office_document_revision",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OfficeDocumentContent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("note", "Note"),
                            ("checklist", "Checklist"),
                            ("sheet", "Sheet"),
                        ],
                        default="document",
                        max_length=16,
                    ),
                ),
                ("content_json", models.JSONField(default=dict)),
                ("revision_number", models.PositiveIntegerField(default=0)),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="office_content",
                        to="documents.document",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_documents_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision_number__gte", 0)),
                        name="office_content_revision_nonnegative",
                    )
                ],
            },
        ),
    ]
