# Generated by Django 5.2.5 on 2026-09-16 11:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_office_collaboration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("management", "Management"),
                    ("bookings", "Bookings"),
                    ("live", "Live"),
                    ("music", "Music"),
                    ("campaign", "Campaign"),
                    ("travel", "Travel"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OfficeSavedSheetView",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("config", models.JSONField(default=dict)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_sheet_views",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_sheet_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "user", "name"), name="unique_saved_sheet_view_name"
                    )
                ],
            },
        ),
    ]
