# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("documents", "0012_office_template_categories_and_saved_views")]

    operations = [
        migrations.AlterField(
            model_name="officedocumentcontent",
            name="format",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("note", "Note"),
                    ("checklist", "Checklist"),
                    ("sheet", "Sheet"),
                    ("presentation", "Presentation"),
                ],
                default="document",
                max_length=16,
            ),
        ),
    ]
