# Generated by Django 5.2.5 on 2026-08-24 14:19

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("province", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=30)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=500)),
                ("public_phone", models.CharField(blank=True, max_length=40)),
                ("public_email", models.EmailField(blank=True, max_length=254)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="VenueContact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "responsibility",
                    models.CharField(
                        choices=[
                            ("venue_manager", "Venue manager"),
                            ("production", "Production"),
                            ("technical", "Technical"),
                            ("hospitality", "Hospitality"),
                            ("security", "Security"),
                            ("finance", "Finance"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=24,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_links",
                        to="contacts.contact",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_links",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "responsibility", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["organization", "status"], name="venues_venu_organiz_9f32c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_venue_slug_per_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="venuecontact",
            constraint=models.UniqueConstraint(
                fields=("venue", "contact"), name="unique_venue_contact_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="venuecontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("venue", "responsibility"),
                name="one_primary_venue_contact_per_role",
            ),
        ),
    ]
