# Generated by Django 5.2.5 on 2026-08-25 12:11

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import rights.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("contacts", "0001_initial"),
        ("documents", "0001_initial"),
        ("music", "0001_initial"),
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RightsParty",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("artist", "Artist"),
                            ("songwriter", "Songwriter"),
                            ("producer", "Producer"),
                            ("publisher", "Publisher"),
                            ("label", "Label"),
                            ("company", "Company"),
                            ("estate", "Estate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(max_length=220)),
                ("external_identifier", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True, max_length=5000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "linked_artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rights_parties",
                        to="artists.artist",
                    ),
                ),
                (
                    "linked_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rights_parties",
                        to="contacts.contact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rights_parties",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("display_name",),
            },
        ),
        migrations.CreateModel(
            name="MasterRight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ownership_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "territory_code",
                    models.CharField(
                        default="WORLDWIDE",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(WORLDWIDE|[A-Z]{2})$",
                                "Use WORLDWIDE or an ISO-style country code.",
                            )
                        ],
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=2000)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="master_rights",
                        to="music.track",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rights.rightsparty"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoyaltyStatement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "statement_reference",
                    models.CharField(
                        default=rights.models.statement_reference,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("source_name", models.CharField(max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("finalized", "Finalized"), ("void", "Void")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "currency",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use an uppercase three-letter currency code."
                            )
                        ],
                    ),
                ),
                (
                    "declared_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
                ),
                ("internal_notes", models.TextField(blank=True, max_length=5000)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="royalty_statements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="royalty_statements_finalized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royalty_statements",
                        to="organizations.organization",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royalty_statements",
                        to="documents.document",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="royalty_statements_voided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-period_end", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="RoyaltyStatementLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_track_reference", models.CharField(blank=True, max_length=180)),
                (
                    "territory_code",
                    models.CharField(
                        default="WORLDWIDE",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(WORLDWIDE|[A-Z]{2})$",
                                "Use WORLDWIDE or an ISO-style country code.",
                            )
                        ],
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=120)),
                ("usage_type", models.CharField(blank=True, max_length=120)),
                (
                    "rights_basis",
                    models.CharField(
                        choices=[
                            ("master", "Master"),
                            ("publishing", "Publishing"),
                            ("mixed", "Mixed"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=16),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royalty_lines",
                        to="artists.artist",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royalty_lines",
                        to="music.release",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="rights.royaltystatement",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royalty_lines",
                        to="music.track",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("alternate_title", models.CharField(blank=True, max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "iswc",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^T\\d{10}$", "ISWC must use normalized T followed by 10 digits."
                            )
                        ],
                    ),
                ),
                ("internal_reference", models.CharField(blank=True, max_length=80)),
                ("language", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True, max_length=5000)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="works_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="works",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="TrackWork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("medley", "Medley"),
                            ("adaptation", "Adaptation"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_links",
                        to="music.track",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="track_links",
                        to="rights.work",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublishingRight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ownership_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "territory_code",
                    models.CharField(
                        default="WORLDWIDE",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(WORLDWIDE|[A-Z]{2})$",
                                "Use WORLDWIDE or an ISO-style country code.",
                            )
                        ],
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=2000)),
                (
                    "right_type",
                    models.CharField(
                        choices=[
                            ("writer", "Writer"),
                            ("publisher", "Publisher"),
                            ("administrator", "Administrator"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rights.rightsparty"
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publishing_rights",
                        to="rights.work",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkContributor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("songwriter", "Songwriter"),
                            ("composer", "Composer"),
                            ("lyricist", "Lyricist"),
                            ("arranger", "Arranger"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_contributions",
                        to="rights.rightsparty",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributors",
                        to="rights.work",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="RoyaltyAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "right_basis",
                    models.CharField(
                        choices=[
                            ("master", "Master"),
                            ("publishing", "Publishing"),
                            ("manual", "Manual"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="royalty_allocations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="royalty_allocations",
                        to="rights.rightsparty",
                    ),
                ),
                (
                    "statement_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="rights.royaltystatementline",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("statement_line", "party", "right_basis"),
                        name="rights_unique_line_party_basis",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="work",
            constraint=models.UniqueConstraint(
                condition=models.Q(("iswc", ""), _negated=True),
                fields=("organization", "iswc"),
                name="rights_unique_work_iswc_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackwork",
            constraint=models.UniqueConstraint(
                fields=("track", "work"), name="rights_unique_track_work"
            ),
        ),
        migrations.AddConstraint(
            model_name="workcontributor",
            constraint=models.UniqueConstraint(
                fields=("work", "party", "role"), name="rights_unique_work_contributor"
            ),
        ),
    ]
