# Generated by Django 5.2.5 on 2026-08-25 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("rights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="works",
                to="documents.document",
            ),
        ),
    ]
