# Generated by Django 5.2.5 on 2026-08-24 15:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("contacts", "0001_initial"),
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallSheet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_sheet",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_sheets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_sheets",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-booking__event_date",),
            },
        ),
        migrations.CreateModel(
            name="CallSheetVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=220)),
                ("subtitle", models.CharField(blank=True, max_length=220)),
                ("event_name", models.CharField(max_length=220)),
                ("artist_name", models.CharField(max_length=220)),
                ("event_date", models.DateField()),
                ("event_start_datetime", models.DateTimeField(blank=True, null=True)),
                ("event_end_datetime", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(max_length=64)),
                ("venue_name", models.CharField(blank=True, max_length=180)),
                ("venue_address", models.CharField(blank=True, max_length=520)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("province", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("venue_phone", models.CharField(blank=True, max_length=40)),
                ("promoter_name", models.CharField(blank=True, max_length=180)),
                ("access_notes", models.TextField(blank=True, max_length=5000)),
                ("loading_access", models.TextField(blank=True, max_length=5000)),
                ("parking_notes", models.TextField(blank=True, max_length=5000)),
                ("backstage_access", models.TextField(blank=True, max_length=5000)),
                ("dressing_room_notes", models.TextField(blank=True, max_length=5000)),
                ("emergency_procedure_notes", models.TextField(blank=True, max_length=5000)),
                ("soundcheck_time", models.TimeField(blank=True, null=True)),
                ("production_contact", models.CharField(blank=True, max_length=220)),
                ("stage_notes", models.TextField(blank=True, max_length=5000)),
                ("technical_notes", models.TextField(blank=True, max_length=5000)),
                ("backline_notes", models.TextField(blank=True, max_length=5000)),
                ("special_requirements", models.TextField(blank=True, max_length=5000)),
                ("catering_notes", models.TextField(blank=True, max_length=5000)),
                ("dietary_notes", models.TextField(blank=True, max_length=5000)),
                ("guest_notes", models.TextField(blank=True, max_length=5000)),
                ("general_notes", models.TextField(blank=True, max_length=10000)),
                ("artist_notes", models.TextField(blank=True, max_length=5000)),
                ("team_notes", models.TextField(blank=True, max_length=5000)),
                ("security_notes", models.TextField(blank=True, max_length=5000)),
                ("emergency_notes", models.TextField(blank=True, max_length=5000)),
                (
                    "call_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="callsheets.callsheet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_sheet_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_sheet_versions_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-version_number",),
            },
        ),
        migrations.CreateModel(
            name="CallSheetTravelItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("ground", "Ground"),
                            ("train", "Train"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=220)),
                ("reference", models.CharField(blank=True, max_length=220)),
                ("departure_location", models.CharField(max_length=220)),
                ("arrival_location", models.CharField(max_length=220)),
                ("departure_datetime", models.DateTimeField()),
                ("arrival_datetime", models.DateTimeField(blank=True, null=True)),
                ("traveler_notes", models.TextField(blank=True, max_length=3000)),
                ("contact_name", models.CharField(blank=True, max_length=220)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True, max_length=3000)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="travel_items",
                        to="callsheets.callsheetversion",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CallSheetTeamEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("name_snapshot", models.CharField(max_length=301)),
                ("role_snapshot", models.CharField(blank=True, max_length=120)),
                ("responsibility_snapshot", models.CharField(blank=True, max_length=220)),
                ("phone_snapshot", models.CharField(blank=True, max_length=40)),
                ("email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("call_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=3000)),
                (
                    "booking_team_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.bookingteamassignment",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.membership",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_entries",
                        to="callsheets.callsheetversion",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CallSheetScheduleItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True, max_length=3000)),
                ("location", models.CharField(blank=True, max_length=220)),
                ("responsibility", models.CharField(blank=True, max_length=220)),
                ("is_highlighted", models.BooleanField(default=False)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_items",
                        to="callsheets.callsheetversion",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CallSheetContactEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("responsibility", models.CharField(max_length=220)),
                ("name_snapshot", models.CharField(max_length=241)),
                ("company_snapshot", models.CharField(blank=True, max_length=220)),
                ("email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("phone_snapshot", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True, max_length=3000)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "source_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.contact",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_entries",
                        to="callsheets.callsheetversion",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CallSheetAccommodationItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("property_name", models.CharField(max_length=220)),
                ("address", models.CharField(blank=True, max_length=520)),
                ("check_in_datetime", models.DateTimeField()),
                ("check_out_datetime", models.DateTimeField(blank=True, null=True)),
                ("confirmation_reference", models.CharField(blank=True, max_length=220)),
                ("contact_name", models.CharField(blank=True, max_length=220)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True, max_length=3000)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accommodation_items",
                        to="callsheets.callsheetversion",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="callsheetversion",
            constraint=models.UniqueConstraint(
                fields=("call_sheet", "version_number"), name="unique_call_sheet_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="callsheetversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("call_sheet",),
                name="one_published_version_per_call_sheet",
            ),
        ),
    ]
