# Generated by Django 5.2.5 on 2026-08-28 15:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedReportView",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("report_key", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=120)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("sort", models.CharField(blank=True, max_length=40)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_report_views",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_report_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("report_key", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user", "report_key", "name"),
                        name="unique_saved_report_name_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("organization", "user", "report_key"),
                        name="one_default_saved_report_per_user",
                    ),
                ],
            },
        ),
    ]
