# Generated by Django 5.2.5 on 2026-08-25 18:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import production.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("bookings", "0001_initial"),
        ("contacts", "0001_initial"),
        ("organizations", "0002_initial"),
        ("promoters", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionAdvance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("production_title", models.CharField(max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In progress"),
                            ("ready", "Ready"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("production_notes", models.TextField(blank=True, max_length=5000)),
                ("access_notes", models.TextField(blank=True, max_length=5000)),
                ("parking_notes", models.TextField(blank=True, max_length=5000)),
                ("security_notes", models.TextField(blank=True, max_length=5000)),
                ("advance_due_at", models.DateTimeField(blank=True, null=True)),
                ("last_advanced_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_advances",
                        to="artists.artist",
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_advance",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_advances_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_advances",
                        to="organizations.organization",
                    ),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_advances",
                        to="promoters.promoter",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_advances",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ("booking__event_date", "production_title"),
            },
        ),
        migrations.CreateModel(
            name="AdvanceRequirement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("hospitality", "Hospitality"),
                            ("backline", "Backline"),
                            ("stage", "Stage"),
                            ("audio", "Audio"),
                            ("lighting", "Lighting"),
                            ("video", "Video"),
                            ("power", "Power"),
                            ("security", "Security"),
                            ("access", "Access"),
                            ("parking", "Parking"),
                            ("catering", "Catering"),
                            ("dressing_room", "Dressing room"),
                            ("merchandise", "Merchandise"),
                            ("guest_list", "Guest list"),
                            ("transport", "Transport"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True, max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("requested", "Requested"),
                            ("in_progress", "In progress"),
                            ("confirmed", "Confirmed"),
                            ("not_applicable", "Not applicable"),
                            ("blocked", "Blocked"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("artist", "Artist"),
                            ("venue", "Venue"),
                            ("promoter", "Promoter"),
                            ("management", "Management"),
                            ("production", "Production"),
                            ("other", "Other"),
                        ],
                        default="production",
                        max_length=20,
                    ),
                ),
                ("response_notes", models.TextField(blank=True, max_length=5000)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_requirements",
                        to="organizations.membership",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_requirements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requirements",
                        to="production.productionadvance",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="AdvanceChecklistItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("technical", "Technical"),
                            ("hospitality", "Hospitality"),
                            ("travel", "Travel"),
                            ("venue", "Venue"),
                            ("promoter", "Promoter"),
                            ("documents", "Documents"),
                            ("finance", "Finance"),
                            ("show_day", "Show day"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True, max_length=3000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_checklist_items",
                        to="organizations.membership",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_checklist_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_items",
                        to="production.productionadvance",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ProductionContactAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("promoter", "Promoter"),
                            ("venue", "Venue"),
                            ("production_manager", "Production manager"),
                            ("technical_manager", "Technical manager"),
                            ("stage_manager", "Stage manager"),
                            ("sound", "Sound"),
                            ("lighting", "Lighting"),
                            ("security", "Security"),
                            ("hospitality", "Hospitality"),
                            ("catering", "Catering"),
                            ("transport", "Transport"),
                            ("merchandise", "Merchandise"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("responsibility", models.CharField(blank=True, max_length=220)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, max_length=3000)),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_assignments",
                        to="production.productionadvance",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_assignments",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "role", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ProductionScheduleItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("venue_access", "Venue access"),
                            ("load_in", "Load in"),
                            ("soundcheck", "Soundcheck"),
                            ("line_check", "Line check"),
                            ("rehearsal", "Rehearsal"),
                            ("catering", "Catering"),
                            ("doors", "Doors"),
                            ("support", "Support"),
                            ("show", "Show"),
                            ("curfew", "Curfew"),
                            ("load_out", "Load out"),
                            ("departure", "Departure"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(
                        max_length=64, validators=[production.models.validate_timezone]
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=220)),
                ("notes", models.TextField(blank=True, max_length=3000)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_items",
                        to="production.productionadvance",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "starts_at"),
            },
        ),
        migrations.AddIndex(
            model_name="productionadvance",
            index=models.Index(
                fields=["organization", "status", "advance_due_at"],
                name="production__organiz_7e44eb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="advancerequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("advance", "sequence"),
                name="unique_active_requirement_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="advancechecklistitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("advance", "sequence"),
                name="unique_active_checklist_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="productioncontactassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("advance", "role"),
                name="one_primary_production_contact_per_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionscheduleitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("advance", "sequence"),
                name="unique_active_production_schedule_sequence",
            ),
        ),
    ]
