# Generated by Django 5.2.5 on 2026-08-28 13:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login.success", "Login successful"),
                            ("login.failure", "Login failed"),
                            ("logout", "Logged out"),
                            ("reauth.success", "Reauthentication successful"),
                            ("reauth.failure", "Reauthentication failed"),
                            ("password.changed", "Password changed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("success", models.BooleanField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_at"], name="users_secur_user_id_bb5c1c_idx"
                    )
                ],
            },
        ),
    ]
