# Generated by Django 5.2.5 on 2026-08-24 16:37

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("contacts", "0001_initial"),
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=140)),
                (
                    "release_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("ep", "EP"),
                            ("album", "Album"),
                            ("mixtape", "Mixtape"),
                            ("compilation", "Compilation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("released", "Released"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("planned_release_date", models.DateField(blank=True, null=True)),
                ("release_datetime", models.DateTimeField(blank=True, null=True)),
                ("original_release_date", models.DateField(blank=True, null=True)),
                ("upc_ean", models.CharField(blank=True, max_length=14)),
                ("catalog_number", models.CharField(blank=True, max_length=80)),
                ("artwork_url", models.URLField(blank=True, max_length=500)),
                ("public_url", models.URLField(blank=True, max_length=500)),
                ("presave_url", models.URLField(blank=True, max_length=500)),
                ("label_name", models.CharField(blank=True, max_length=180)),
                ("distributor_name", models.CharField(blank=True, max_length=180)),
                ("internal_notes", models.TextField(blank=True, max_length=10000)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="music_releases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="music_releases",
                        to="organizations.organization",
                    ),
                ),
                (
                    "primary_artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="music_releases",
                        to="artists.artist",
                    ),
                ),
            ],
            options={
                "ordering": ("-planned_release_date", "title"),
            },
        ),
        migrations.CreateModel(
            name="ReleaseLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("spotify", "Spotify"),
                            ("apple_music", "Apple Music"),
                            ("youtube", "YouTube"),
                            ("deezer", "Deezer"),
                            ("audiomack", "Audiomack"),
                            ("boomplay", "Boomplay"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="music.release",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "platform"),
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("version_title", models.CharField(blank=True, max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("isrc", models.CharField(blank=True, max_length=12)),
                ("internal_reference", models.CharField(blank=True, max_length=80)),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("explicit_content", models.BooleanField(default=False)),
                ("artwork_url", models.URLField(blank=True, max_length=500)),
                ("audio_preview_url", models.URLField(blank=True, max_length=500)),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2200),
                        ],
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=80)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("subgenre", models.CharField(blank=True, max_length=100)),
                ("internal_notes", models.TextField(blank=True, max_length=10000)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="music_tracks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="music_tracks",
                        to="organizations.organization",
                    ),
                ),
                (
                    "primary_artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="music_tracks",
                        to="artists.artist",
                    ),
                ),
            ],
            options={
                "ordering": ("title", "version_title"),
            },
        ),
        migrations.CreateModel(
            name="ReleaseTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("disc_number", models.PositiveSmallIntegerField(default=1)),
                ("track_number", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("is_focus_track", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="track_placements",
                        to="music.release",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_placements",
                        to="music.track",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "disc_number", "track_number"),
            },
        ),
        migrations.CreateModel(
            name="MusicCredit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=241)),
                (
                    "credit_role",
                    models.CharField(
                        choices=[
                            ("primary_artist", "Primary artist"),
                            ("featured_artist", "Featured artist"),
                            ("producer", "Producer"),
                            ("songwriter", "Songwriter"),
                            ("composer", "Composer"),
                            ("mix_engineer", "Mix engineer"),
                            ("mastering_engineer", "Mastering engineer"),
                            ("executive_producer", "Executive producer"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=1)),
                (
                    "linked_artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="music_credits",
                        to="artists.artist",
                    ),
                ),
                (
                    "linked_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="music_credits",
                        to="contacts.contact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="music_credits",
                        to="organizations.organization",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="music.release",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="music.track",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["organization", "status", "planned_release_date"],
                name="music_relea_organiz_5b2873_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_release_slug_per_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                condition=models.Q(("upc_ean", ""), _negated=True),
                fields=("upc_ean",),
                name="unique_nonempty_release_upc",
            ),
        ),
        migrations.AddConstraint(
            model_name="releaselink",
            constraint=models.UniqueConstraint(
                fields=("release", "platform", "url"), name="unique_release_platform_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="releaselink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("release",),
                name="one_primary_link_per_release",
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["organization", "primary_artist", "status"],
                name="music_track_organiz_516f6c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_track_slug_per_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                condition=models.Q(("isrc", ""), _negated=True),
                fields=("isrc",),
                name="unique_nonempty_track_isrc",
            ),
        ),
        migrations.AddConstraint(
            model_name="releasetrack",
            constraint=models.UniqueConstraint(
                fields=("release", "track"), name="unique_track_placement_per_release"
            ),
        ),
        migrations.AddConstraint(
            model_name="releasetrack",
            constraint=models.UniqueConstraint(
                fields=("release", "disc_number", "track_number"),
                name="unique_release_disc_track_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="musiccredit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("release__isnull", False), ("track__isnull", False), _connector="OR"
                ),
                name="music_credit_has_release_or_track",
            ),
        ),
    ]
